# (PART) Software {.unnumbered}

# Introduction to Shell {.unnumbered}

**Course Description**

<p class="course__description">The Unix command line has survived and thrived for almost 50 years because it lets people do complex things with just a few keystrokes. Sometimes called "the universal glue of programming," it helps users combine existing programs in new ways, automate repetitive tasks, and run programs on clusters and clouds that may be halfway around the world. This course will introduce its key elements and show you how to use them efficiently.</p>

### Manipulating files and directories {.unnumbered}

This chapter is a brief introduction to the Unix shell. You'll learn why it is still in use after almost 50 years, how it compares to the graphical tools you may be more familiar with, how to move around in the shell, and how to create, modify, and delete files and folders.

#### Shell compares to a desktop? {.unnumbered}

<div class=""><p>An operating system like Windows, Linux, or Mac OS is a special kind of program.
It controls the computer's processor, hard drive, and network connection,
but its most important job is to run other programs.</p>
<p>Since human beings aren't digital,
they need an interface to interact with the operating system.
The most common one these days is a graphical file explorer,
which translates clicks and double-clicks into commands to open files and run programs.
Before computers had graphical displays,
though,
people typed instructions into a program called a <strong>command-line shell</strong>.
Each time a command is entered,
the shell runs some other programs,
prints their output in human-readable form,
and then displays a <em>prompt</em> to signal that it's ready to accept the next command.
(Its name comes from the notion that it's the "outer shell" of the computer.)</p>
<p>Typing commands instead of clicking and dragging may seem clumsy at first,
but as you will see,
once you start spelling out what you want the computer to do,
you can combine old commands to create new ones
and automate repetitive operations
with just a few keystrokes.</p>
<p></p><hr>
What is the relationship between the graphical file explorer that most people use and the command-line shell?<p></p></div>

- [ ] The file explorer lets you view and edit files, while the shell lets you run programs.
- [ ] The file explorer is built on top of the shell.
- [ ] The shell is part of the operating system, while the file explorer is separate.
- [x] They are both interfaces for issuing commands to the operating system.

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct! Both take the user's commands (whether typed or clicked) and send them to the operating system.</p>

#### Where am I? {.unnumbered}


<div class>
<p>The <strong>filesystem</strong> manages files and directories (or folders).
Each is identified by an <strong>absolute path</strong>
that shows how to reach it from the filesystem's <strong>root directory</strong>:
<code>/home/repl</code> is the directory <code>repl</code> in the directory <code>home</code>,
while <code>/home/repl/course.txt</code> is a file <code>course.txt</code> in that directory,
and <code>/</code> on its own is the root directory.</p>
<p>To find out where you are in the filesystem,
run the command <code>pwd</code>
(short for "<strong>p</strong>rint <strong>w</strong>orking <strong>d</strong>irectory").
This prints the absolute path of your <strong>current working directory</strong>,
which is where the shell runs commands and looks for files by default.</p>
<p></p>
<hr>
Run <code>pwd</code>.
Where are you right now?</div>

```{sh,eval=F}
pwd
```

- [ ] <code>/home</code>
- [ ] <code>/repl</code>
- [x] <code>/home/repl</code>

<p class="">Neat! This was about navigating down to subdirectories. What about moving up? Let's find out!</p>

#### Identify files and directories? {.unnumbered}


<div class>
<p><code>pwd</code> tells you where you are.
To find out what's there,
type <code>ls</code> (which is short for "<strong>l</strong>i<strong>s</strong>ting") and press the enter key.
On its own,
<code>ls</code> lists the contents of your current directory
(the one displayed by <code>pwd</code>).
If you add the names of some files,
<code>ls</code> will list them,
and if you add the names of directories,
it will list their contents.
For example,
<code>ls /home/repl</code> shows you what's in your starting directory
(usually called your <strong>home directory</strong>).</p>
<p></p>
<hr>
Use <code>ls</code> with an appropriate argument to list the files in the directory <code>/home/repl/seasonal</code>
(which holds information on dental surgeries by date, broken down by season).
Which of these files is <em>not</em> in that directory?</div>

```{sh,eval=F}
ls seasonal
```

- [ ] <code>autumn.csv</code>
- [x] <code>fall.csv</code>
- [ ] <code>spring.csv</code>
- [ ] <code>winter.csv</code>

<p class="">Correct - that file is <em>not</em> in the <code>seasonal</code> directory.</p>

#### Identify files and directories? {.unnumbered}


<div class>
<p>An absolute path is like a latitude and longitude: it has the same value no matter where you are. A <strong>relative path</strong>, on the other hand, specifies a location starting from where you are: it's like saying "20 kilometers north".</p>
<p>As examples:</p>
<ul>
<li>If you are in the directory <code>/home/repl</code>, the <strong>relative</strong> path <code>seasonal</code> specifies the same directory as the <strong>absolute</strong> path <code>/home/repl/seasonal</code>. </li>
<li>If you are in the directory <code>/home/repl/seasonal</code>, the <strong>relative</strong> path <code>winter.csv</code> specifies the same file as the <strong>absolute</strong> path <code>/home/repl/seasonal/winter.csv</code>.</li>
</ul>
<p>The shell decides if a path is absolute or relative by looking at its first character: If it begins with <code>/</code>, it is absolute. If it <em>does not</em> begin with <code>/</code>, it is relative.</p>
</div>
<div class="exercise--instructions__content"><p>You are in <code>/home/repl</code>. Use <code>ls</code> with a <strong>relative path</strong> to list the file that has an absolute path of <code>/home/repl/course.txt</code> (and only that file).</p></div>
```{sh,eval=F}
ls course.txt
```
<div class="exercise--instructions__content"><p>You are in <code>/home/repl</code>.
Use <code>ls</code> with a <strong>relative</strong> path
to list the file <code>/home/repl/seasonal/summer.csv</code> (and only that file).</p></div>
```{sh,eval=F}
ls seasonal/summer.csv
```
<div class="exercise--instructions__content"><p>You are in <code>/home/repl</code>.
Use <code>ls</code> with a <strong>relative</strong> path
to list the contents of the directory <code>/home/repl/people</code>.</p></div>
```{sh,eval=F}
ls people
```

<p class="">Well done. Now that you know about listing files and directories, let's see how you can move around the filesystem!</p>

#### Move to another directory? {.unnumbered}


<div class>
<p>Just as you can move around in a file browser by double-clicking on folders,
you can move around in the filesystem using the command <code>cd</code>
(which stands for "change directory").</p>
<p>If you type <code>cd seasonal</code> and then type <code>pwd</code>,
the shell will tell you that you are now in <code>/home/repl/seasonal</code>.
If you then run <code>ls</code> on its own,
it shows you the contents of <code>/home/repl/seasonal</code>,
because that's where you are.
If you want to get back to your home directory <code>/home/repl</code>,
you can use the command <code>cd /home/repl</code>.</p>
</div>
<div class="exercise--instructions__content"><p>You are in <code>/home/repl</code>/.
Change directory to <code>/home/repl/seasonal</code> using a relative path.</p></div>
```{sh,eval=F}
cd seasonal
```
<div class="exercise--instructions__content"><p>Use <code>pwd</code> to check that you're there.</p></div>
```{sh,eval=F}
pwd
```
<div class="exercise--instructions__content"><p>Use <code>ls</code> without any paths to see what's in that directory.</p></div>
```{sh,eval=F}
ls
```

<p class="">Neat! This was about navigating down to subdirectories. What about moving up? Let's find out!</p>

#### Move up a directory? {.unnumbered}

<div class=""><p>The <strong>parent</strong> of a directory is the directory above it.
For example, <code>/home</code> is the parent of <code>/home/repl</code>,
and <code>/home/repl</code> is the parent of <code>/home/repl/seasonal</code>.
You can always give the absolute path of your parent directory to commands like <code>cd</code> and <code>ls</code>.
More often,
though,
you will take advantage of the fact that the special path <code>..</code>
(two dots with no spaces) means "the directory above the one I'm currently in".
If you are in <code>/home/repl/seasonal</code>,
then <code>cd ..</code> moves you up to <code>/home/repl</code>.
If you use <code>cd ..</code> once again,
it puts you in <code>/home</code>.
One more <code>cd ..</code> puts you in the <em>root directory</em> <code>/</code>,
which is the very top of the filesystem.
(Remember to put a space between <code>cd</code> and <code>..</code> - it is a command and a path, not a single four-letter command.)</p>
<p>A single dot on its own, <code>.</code>, always means "the current directory",
so <code>ls</code> on its own and <code>ls .</code> do the same thing,
while <code>cd .</code> has no effect
(because it moves you into the directory you're currently in).</p>
<p>One final special path is <code>~</code> (the tilde character),
which means "your home directory",
such as <code>/home/repl</code>.
No matter where you are,
<code>ls ~</code> will always list the contents of your home directory,
and <code>cd ~</code> will always take you home.</p>
<p></p><hr>
If you are in <code>/home/repl/seasonal</code>,
where does <code>cd ~/../.</code> take you?<p></p></div>

- [ ] <code>/home/repl</code>
- [x] <code>/home</code>
- [ ] <code>/home/repl/seasonal</code>
- [ ] <code>/</code> (the root directory)

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct! The path means 'home directory', 'up a level', 'here'.</p>

#### Copy files? {.unnumbered}


<div class>
<p>You will often want to copy files,
move them into other directories to organize them,
or rename them.
One command to do this is <code>cp</code>, which is short for "copy".
If <code>original.txt</code> is an existing file,
then:</p>
<pre><code>cp original.txt duplicate.txt
</code></pre>
<p>creates a copy of <code>original.txt</code> called <code>duplicate.txt</code>.
If there already was a file called <code>duplicate.txt</code>,
it is overwritten.
If the last parameter to <code>cp</code> is an existing directory,
then a command like:</p>
<pre><code>cp seasonal/autumn.csv seasonal/winter.csv backup
</code></pre>
<p>copies <em>all</em> of the files into that directory.</p>
</div>
<div class="exercise--instructions__content"><p>Make a copy of <code>seasonal/summer.csv</code> in the <code>backup</code> directory (which is also in <code>/home/repl</code>),
calling the new file <code>summer.bck</code>.</p></div>
```{sh,eval=F}
cp seasonal/summer.csv backup/summer.bck
```

<div class="exercise--instructions__content"><p>Copy <code>spring.csv</code> and <code>summer.csv</code> from the <code>seasonal</code> directory into the <code>backup</code> directory
<em>without</em> changing your current working directory (<code>/home/repl</code>).</p></div>

```{sh,eval=F}
cp seasonal/spring.csv seasonal/summer.csv backup
```

<p class="">Good job. Other than copying, we should also be able to move files from one directory to another. Learn about it in the next exercise!</p>

#### Move a file? {.unnumbered}


<div class>
<p>While <code>cp</code> copies a file,
<code>mv</code> moves it from one directory to another,
just as if you had dragged it in a graphical file browser.
It handles its parameters the same way as <code>cp</code>,
so the command:</p>
<pre><code>mv autumn.csv winter.csv ..
</code></pre>
<p>moves the files <code>autumn.csv</code> and <code>winter.csv</code> from the current working directory
up one level to its parent directory
(because <code>..</code> always refers to the directory above your current location).</p>
</div>
<div class="exercise--instructions__content"><p>You are in <code>/home/repl</code>, which has sub-directories <code>seasonal</code> and <code>backup</code>.
Using a single command, move <code>spring.csv</code> and <code>summer.csv</code> from <code>seasonal</code> to <code>backup</code>.</p></div>
```{sh,eval=F}
cd home/repl
mv seasonal/spring.csv seasonal/summer.csv backup
```

<p class="">Well done, let's keep this shell train going!</p>

#### Rename files? {.unnumbered}


<div class>
<p><code>mv</code> can also be used to rename files. If you run:</p>
<pre><code>mv course.txt old-course.txt
</code></pre>
<p>then the file <code>course.txt</code> in the current working directory is "moved" to the file <code>old-course.txt</code>.
This is different from the way file browsers work,
but is often handy.</p>
<p>One warning:
just like <code>cp</code>,
<code>mv</code> will overwrite existing files.
If,
for example,
you already have a file called <code>old-course.txt</code>,
then the command shown above will replace it with whatever is in <code>course.txt</code>.</p>
</div>
<div class="exercise--instructions__content"><p>Go into the <code>seasonal</code> directory.</p></div>
```{sh,eval=F}
cd seasonal
```
<div class="exercise--instructions__content"><p>Rename the file <code>winter.csv</code> to be <code>winter.csv.bck</code>.</p></div>
```{sh,eval=F}
mv winter.csv winter.csv.bck
```

<div class="exercise--instructions__content"><p>Run <code>ls</code> to check that everything has worked.</p></div>
```{sh,eval=F}
ls
```

<p class="">Copying, moving, renaming, you've all got it figured out! Next up: deleting files.</p>

#### Delete files? {.unnumbered}


<div class>
<p>We can copy files and move them around;
to delete them,
we use <code>rm</code>,
which stands for "remove".
As with <code>cp</code> and <code>mv</code>,
you can give <code>rm</code> the names of as many files as you'd like, so:</p>
<pre><code>rm thesis.txt backup/thesis-2017-08.txt
</code></pre>
<p>removes both <code>thesis.txt</code> and <code>backup/thesis-2017-08.txt</code></p>
<p><code>rm</code> does exactly what its name says,
and it does it right away:
unlike graphical file browsers,
the shell doesn't have a trash can,
so when you type the command above,
your thesis is gone for good.</p>
</div>
<div class="exercise--instructions__content"><p>You are in <code>/home/repl</code>.
Go into the <code>seasonal</code> directory.</p></div>
```{sh,eval=F}
cd seasonal
```
<div class="exercise--instructions__content"><p>Remove <code>autumn.csv</code>.</p></div>
```{sh,eval=F}
rm autumn.csv
```
<div class="exercise--instructions__content"><p>Go back to your home directory.</p></div>
```{sh,eval=F}
cd
```
<div class="exercise--instructions__content"><p>Remove <code>seasonal/summer.csv</code> without changing directories again.</p></div>
```{sh,eval=F}
rm seasonal/summer.csv
```

<p class="">Impressive stuff! Off to the next one!</p>

#### Create and delete directories? {.unnumbered}


<div class>
<p><code>mv</code> treats directories the same way it treats files:
if you are in your home directory and run <code>mv seasonal by-season</code>,
for example,
<code>mv</code> changes the name of the <code>seasonal</code> directory to <code>by-season</code>.
However,
<code>rm</code> works differently.</p>
<p>If you try to <code>rm</code> a directory,
the shell prints an error message telling you it can't do that,
primarily to stop you from accidentally deleting an entire directory full of work.
Instead,
you can use a separate command called <code>rmdir</code>.
For added safety,
it only works when the directory is empty,
so you must delete the files in a directory <em>before</em> you delete the directory.
(Experienced users can use the <code>-r</code> option to <code>rm</code> to get the same effect;
we will discuss command options in the next chapter.)</p>
</div>
<div class="exercise--instructions__content"><p>Without changing directories,
delete the file <code>agarwal.txt</code> in the <code>people</code> directory.</p></div>
```{sh,eval=F}
rm people/agarwal.txt
```
<div class="exercise--instructions__content"><p>Now that the <code>people</code> directory is empty,
use a single command to delete it.</p></div>
```{sh,eval=F}
rmdir people
```
<div class="exercise--instructions__content"><p>Since a directory is not a file,
you must use the command <code>mkdir directory_name</code>
to create a new (empty) directory.
Use this command to create a new directory called <code>yearly</code> below your home directory.</p></div>
```{sh,eval=F}
mkdir yearly
```
<div class="exercise--instructions__content"><p>Now that <code>yearly</code> exists,
create another directory called <code>2017</code> inside it
<em>without</em> leaving your home directory.</p></div>
```{sh,eval=F}
mkdir yearly/2017
```

<p class="">Cool! Let's wrap up this chapter with an exercise that repeats some of its concepts!</p>

#### Wrapping up {.unnumbered}


<div class><p>You will often create intermediate files when analyzing data.
Rather than storing them in your home directory,
you can put them in <code>/tmp</code>,
which is where people and programs often keep files they only need briefly.
(Note that <code>/tmp</code> is immediately below the root directory <code>/</code>,
<em>not</em> below your home directory.)
This wrap-up exercise will show you how to do that.</p></div>
<div class="exercise--instructions__content"><p>Use <code>cd</code> to go into <code>/tmp</code>.</p></div>
```{sh,eval=F}
cd /tmp
```
<div class="exercise--instructions__content"><p>List the contents of <code>/tmp</code> <em>without</em> typing a directory name.</p></div>
```{sh,eval=F}
ls
```
<div class="exercise--instructions__content"><p>Make a new directory inside <code>/tmp</code> called <code>scratch</code>.</p></div>
```{sh,eval=F}
mkdir scratch
```
<div class="exercise--instructions__content"><p>Move <code>/home/repl/people/agarwal.txt</code> into <code>/tmp/scratch</code>.
We suggest you use the <code>~</code> shortcut for your home directory and a relative path for the second rather than the absolute path.</p></div>
```{sh,eval=F}
mv ~/people/agarwal.txt scratch
```

<p class="">This concludes Chapter 1 of Introduction to Shell! Rush over to the next chapter to learn more about manipulating data!</p>

### Manipulating data {.unnumbered}

The commands you saw in the previous chapter allowed you to move things around in the filesystem. This chapter will show you how to work with the data in those files. The tools we’ll use are fairly simple, but are solid building blocks.

#### View a file's contents? {.unnumbered}


<div class>
<p>Before you rename or delete files,
you may want to have a look at their contents.
The simplest way to do this is with <code>cat</code>,
which just prints the contents of files onto the screen.
(Its name is short for "concatenate", meaning "to link things together",
since it will print all the files whose names you give it, one after the other.)</p>
<pre><code>cat agarwal.txt
</code></pre>
<pre><code>name: Agarwal, Jasmine
position: RCT2
start: 2017-04-01
benefits: full
</code></pre>
</div>
<div class="exercise--instructions__content"><p>Print the contents of <code>course.txt</code> to the screen.</p></div>
```{sh,eval=F}
cat course.txt
```

<p class="">Nice! Let's look at other ways to view a file's contents.</p>

#### File's contents piece by piece? {.unnumbered}


<div class>
<p>You can use <code>cat</code> to print large files and then scroll through the output,
but it is usually more convenient to <strong>page</strong> the output.
The original command for doing this was called <code>more</code>,
but it has been superseded by a more powerful command called <code>less</code>.
(This kind of naming is what passes for humor in the Unix world.)
When you <code>less</code> a file,
one page is displayed at a time;
you can press spacebar to page down or type <code>q</code> to quit.</p>
<p>If you give <code>less</code> the names of several files,
you can type <code>:n</code> (colon and a lower-case 'n') to move to the next file,
<code>:p</code> to go back to the previous one,
or <code>:q</code> to quit.</p>
<p>Note: If you view solutions to exercises that use <code>less</code>,
you will see an extra command at the end that turns paging <em>off</em>
so that we can test your solutions efficiently.</p>
</div>
<div class="exercise--instructions__content"><p>Use <code>less seasonal/spring.csv seasonal/summer.csv</code> to view those two files in that order.
Press spacebar to page down, <code>:n</code> to go to the second file, and <code>:q</code> to quit.</p></div>
```{sh,eval=F}
# You can leave out the '| cat' part here:
less seasonal/spring.csv seasonal/summer.csv | cat
```

<p class="">Great work!</p>

#### Look at the start of a file? {.unnumbered}


<div class>
<p>The first thing most data scientists do when given a new dataset to analyze is
figure out what fields it contains and what values those fields have.
If the dataset has been exported from a database or spreadsheet,
it will often be stored as <strong>comma-separated values</strong> (CSV).
A quick way to figure out what it contains is to look at the first few rows.</p>
<p>We can do this in the shell using a command called <code>head</code>.
As its name suggests,
it prints the first few lines of a file
(where "a few" means 10),
so the command:</p>
<pre><code>head seasonal/summer.csv
</code></pre>
<p>displays:</p>
<pre><code>Date,Tooth
2017-01-11,canine
2017-01-18,wisdom
2017-01-21,bicuspid
2017-02-02,molar
2017-02-27,wisdom
2017-02-27,wisdom
2017-03-07,bicuspid
2017-03-15,wisdom
2017-03-20,canine
</code></pre>
<hr>
<p>What does <code>head</code> do if there aren't 10 lines in the file?
(To find out, use it to look at the top of <code>people/agarwal.txt</code>.)</p>
</div>

- [ ] Print an error message because the file is too short.
- [x] Display as many lines as there are.
- [ ] Display enough blank lines to bring the total to 10.

<p class="">Correct!</p>

#### Type less? {.unnumbered}


<div class>
<p>One of the shell's power tools is <strong>tab completion</strong>.
If you start typing the name of a file and then press the tab key,
the shell will do its best to auto-complete the path.
For example,
if you type <code>sea</code> and press tab,
it will fill in the directory name <code>seasonal/</code> (with a trailing slash).
If you then type <code>a</code> and tab,
it will complete the path as <code>seasonal/autumn.csv</code>.</p>
<p>If the path is ambiguous,
such as <code>seasonal/s</code>,
pressing tab a second time will display a list of possibilities.
Typing another character or two to make your path more specific
and then pressing tab
will fill in the rest of the name.</p>
</div>
<div class="exercise--instructions__content"><p>Run <code>head seasonal/autumn.csv</code> without typing the full filename.</p></div>
```{sh,eval=F}
head seasonal/autumn.csv
```

<div class="exercise--instructions__content"><p>Run <code>head seasonal/spring.csv</code> without typing the full filename.</p></div>
```{sh,eval=F}
head seasonal/spring.csv
```

<p class="">Good work! Once you get used to using tab completion, it will save you a lot of time!</p>

#### Control what commands do? {.unnumbered}


<div class>
<p>You won't always want to look at the first 10 lines of a file,
so the shell lets you change <code>head</code>'s behavior
by giving it a <strong>command-line flag</strong> (or just "flag" for short).
If you run the command:</p>
<pre><code>head -n 3 seasonal/summer.csv
</code></pre>
<p><code>head</code> will only display the first three lines of the file.
If you run <code>head -n 100</code>,
it will display the first 100 (assuming there are that many),
and so on.</p>
<p>A flag's name usually indicates its purpose
(for example, <code>-n</code> is meant to signal "<strong>n</strong>umber of lines").
Command flags don't have to be a <code>-</code> followed by a single letter,
but it's a widely-used convention.</p>
<p>Note: it's considered good style to put all flags <em>before</em> any filenames,
so in this course,
we only accept answers that do that.</p>
</div>
<div class="exercise--instructions__content"><p>Display the first 5 lines of <code>winter.csv</code> in the <code>seasonal</code> directory.</p></div>
```{sh,eval=F}
head -n 5 seasonal/winter.csv

```

<p class="">Nice! With this technique, you can avoid your shell from blowing up if you want to have a look at larger text files.</p>

#### ls below a directory? {.unnumbered}


<div class>
<p>In order to see everything underneath a directory,
no matter how deeply nested it is,
you can give <code>ls</code> the flag <code>-R</code>
(which means "recursive").
If you use <code>ls -R</code> in your home directory,
you will see something like this:</p>
<pre><code>backup          course.txt      people          seasonal

./backup:

./people:
agarwal.txt

./seasonal:
autumn.csv      spring.csv      summer.csv      winter.csv
</code></pre>
<p>This shows every file and directory in the current level,
then everything in each sub-directory,
and so on.</p>
</div>
<div class="exercise--instructions__content"><p>To help you know what is what,
<code>ls</code> has another flag <code>-F</code> that prints a <code>/</code> after the name of every directory
and a <code>*</code> after the name of every runnable program.
Run <code>ls</code> with the two flags, <code>-R</code> and <code>-F</code>, and the absolute path to your home directory
to see everything it contains.
(The order of the flags doesn't matter, but the directory name must come last.)</p></div>
```{sh,eval=F}
ls -R -F /home/repl

```

<p class="">That's a pretty neat overview, isn't it?</p>

#### Get help for a command? {.unnumbered}


<div class>
<p>To find out what commands do,
people used to use the <code>man</code> command
(short for "manual").
For example,
the command <code>man head</code> brings up this information:</p>
<pre><code>HEAD(1)               BSD General Commands Manual              HEAD(1)

NAME
     head -- display first lines of a file

SYNOPSIS
     head [-n count | -c bytes] [file ...]

DESCRIPTION
     This filter displays the first count lines or bytes of each of
     the specified files, or of the standard input if no files are
     specified.  If count is omitted it defaults to 10.

     If more than a single file is specified, each file is preceded by
     a header consisting of the string ``==&gt; XXX &lt;=='' where ``XXX''
     is the name of the file.

SEE ALSO
     tail(1)
</code></pre>
<p><code>man</code> automatically invokes <code>less</code>,
so you may need to press spacebar to page through the information
and <code>:q</code> to quit.</p>
<p>The one-line description under <code>NAME</code> tells you briefly what the command does,
and the summary under <code>SYNOPSIS</code> lists all the flags it understands.
Anything that is optional is shown in square brackets <code>[...]</code>,
either/or alternatives are separated by <code>|</code>,
and things that can be repeated are shown by <code>...</code>,
so <code>head</code>'s manual page is telling you that you can <em>either</em> give a line count with <code>-n</code>
or a byte count with <code>-c</code>,
and that you can give it any number of filenames.</p>
<p>The problem with the Unix manual is that you have to know what you're looking for.
If you don't,
you can search <a href="https://stackoverflow.com/">Stack Overflow</a>,
ask a question on DataCamp's Slack channels,
or look at the <code>SEE ALSO</code> sections of the commands you already know.</p>
</div>
<div class="exercise--instructions__content"><p>Read the manual page for the <code>tail</code> command to find out
what putting a <code>+</code> sign in front of the number used with the <code>-n</code> flag does.
(Remember to press spacebar to page down and/or type <code>q</code> to quit.)</p></div>
```{sh,eval=F}
# Run the following command *without* '| cat':
man tail | cat
```

<div class="exercise--instructions__content"><p>Use <code>tail</code> with the flag <code>-n +7</code> to display all <em>but</em> the first six lines of <code>seasonal/spring.csv</code>.</p></div>
```{sh,eval=F}
tail -n +7 seasonal/spring.csv
```

<p class="">Great work!</p>

#### Select columns from a file? {.unnumbered}


<div class>
<p><code>head</code> and <code>tail</code> let you select rows from a text file.
If you want to select columns,
you can use the command <code>cut</code>.
It has several options (use <code>man cut</code> to explore them),
but the most common is something like:</p>
<pre><code>cut -f 2-5,8 -d , values.csv
</code></pre>
<p>which means
"select columns 2 through 5 and columns 8,
using comma as the separator".
<code>cut</code> uses <code>-f</code> (meaning "fields") to specify columns
and <code>-d</code> (meaning "delimiter") to specify the separator.
You need to specify the latter because some files may use spaces, tabs, or colons to separate columns.</p>
<hr>
<p>What command will select the first column (containing dates) from the  file <code>spring.csv</code>?</p>
</div>

- [ ] <code>cut -d , -f 1 seasonal/spring.csv</code>
- [ ] <code>cut -d, -f1 seasonal/spring.csv</code>
- [x] Either of the above.
- [ ] Neither of the above, because <code>-f</code> must come before <code>-d</code>.

<p class="">Correct! Adding a space after the flag is good style, but not compulsory.</p>

#### What can't cut do? {.unnumbered}


<div class>
<p><code>cut</code> is a simple-minded command.
In particular,
it doesn't understand quoted strings.
If, for example, your file is:</p>
<pre><code>Name,Age
"Johel,Ranjit",28
"Sharma,Rupinder",26
</code></pre>
<p>then:</p>
<pre><code>cut -f 2 -d , everyone.csv
</code></pre>
<p>will produce:</p>
<pre><code>Age
Ranjit"
Rupinder"
</code></pre>
<p>rather than everyone's age,
because it will think the comma between last and first names is a column separator.</p>
<hr>
<p>What is the output of <code>cut -d : -f 2-4</code> on the line:</p>
<pre><code>first:second:third:
</code></pre>
<p>(Note the trailing colon.)</p>
</div>

- [ ] <code>second</code>
- [ ] <code>second:third</code>
- [ ] <code>second:third:</code>
- [ ] None of the above, because there aren't four fields.

<p class="">Correct! The trailing colon creates an empty fourth field.</p>

#### Repeat commands? {.unnumbered}


<div class>
<p>One of the biggest advantages of using the shell is that
it makes it easy for you to do things over again.
If you run some commands,
you can then press the up-arrow key to cycle back through them.
You can also use the left and right arrow keys and the delete key to edit them.
Pressing return will then run the modified command.</p>
<p>Even better, <code>history</code> will print a list of commands you have run recently.
Each one is preceded by a serial number to make it easy to re-run particular commands:
just type <code>!55</code> to re-run the 55th command in your history (if you have that many).
You can also re-run a command by typing an exclamation mark followed by the command's name,
such as <code>!head</code> or <code>!cut</code>,
which will re-run the most recent use of that command.</p>
</div>
<div class="exercise--instructions__content"><p>Run <code>head summer.csv</code> in your home directory (which should fail).</p></div>
```{sh,eval=F}
head summer.csv

```
<div class="exercise--instructions__content"><p>Change directory to <code>seasonal</code>.</p></div>
```{sh,eval=F}
cd seasonal

```
<div class="exercise--instructions__content"><p>Re-run the <code>head</code> command with <code>!head</code>.</p></div>
```{sh,eval=F}
!head

```
<div class="exercise--instructions__content"><p>Use <code>history</code> to look at what you have done.</p></div>
```{sh,eval=F}
history
```
<div class="exercise--instructions__content"><p>Re-run <code>head</code> again using <code>!</code> followed by a command number.</p></div>
```{sh,eval=F}
!3
```

<p class="">Well done! To the next one!</p>

#### Lines containing specific values? {.unnumbered}


<div class>
<p><code>head</code> and <code>tail</code> select rows,
<code>cut</code> selects columns,
and <code>grep</code> selects lines according to what they contain.
In its simplest form,
<code>grep</code> takes a piece of text followed by one or more filenames
and prints all of the lines in those files that contain that text.
For example,
<code>grep bicuspid seasonal/winter.csv</code>
prints lines from <code>winter.csv</code> that contain "bicuspid".</p>
<p><code>grep</code> can search for patterns as well;
we will explore those in the next course.
What's more important right now is some of <code>grep</code>'s more common flags:</p>
<ul>
<li>
<code>-c</code>: print a count of matching lines rather than the lines themselves</li>
<li>
<code>-h</code>: do <em>not</em> print the names of files when searching multiple files</li>
<li>
<code>-i</code>: ignore case (e.g., treat "Regression" and "regression" as matches)</li>
<li>
<code>-l</code>: print the names of files that contain matches, not the matches</li>
<li>
<code>-n</code>: print line numbers for matching lines</li>
<li>
<code>-v</code>: invert the match, i.e., only show lines that <em>don't</em> match</li>
</ul>
</div>
<div class="exercise--instructions__content"><p>Print the contents of all of the lines containing the word <code>molar</code> in <code>seasonal/autumn.csv</code>
by running a single command while in your home directory. Don't use any flags.</p></div>
```{sh,eval=F}
grep molar seasonal/autumn.csv
```

<div class="exercise--instructions__content"><p>Invert the match to find all of the lines that <em>don't</em> contain the word <code>molar</code> in <code>seasonal/spring.csv</code>, and show their line numbers.
Remember, it's considered good style to put all of the flags <em>before</em> other values like filenames or the search term "molar".</p></div>
```{sh,eval=F}
grep -v -n molar seasonal/spring.csv

```

<div class="exercise--instructions__content"><p>Count how many lines contain the word <code>incisor</code> in <code>autumn.csv</code> and <code>winter.csv</code> combined.
(Again, run a single command from your home directory.)</p></div>
```{sh,eval=F}
grep -c incisor seasonal/autumn.csv seasonal/winter.csv

```

<p class="">Great work!</p>

#### Why isn't it always safe to treat data as text? {.unnumbered}


<div class>
<p>The <code>SEE ALSO</code> section of the manual page for <code>cut</code> refers to a command called <code>paste</code>
that can be used to combine data files instead of cutting them up.</p>
<hr>
<p>Read the manual page for <code>paste</code>,
and then run <code>paste</code> to combine the autumn and winter data files in a single table
using a comma as a separator.
What's wrong with the output from a data analysis point of view?</p>
</div>

- [ ] The column headers are repeated.
- [x] The last few rows have the wrong number of columns.
- [ ] Some of the data from <code>winter.csv</code> is missing.

<p class="">Correct: joining the lines with columns creates only one empty column at the start, not two.</p>

### Combining tools {.unnumbered}

The real power of the Unix shell lies not in the individual commands, but in how easily they can be combined to do new things. This chapter will show you how to use this power to select the data you want, and introduce commands for sorting values and removing duplicates.

#### Command's output in a file? {.unnumbered}


<div class>
<p>All of the tools you have seen so far let you name input files.
Most don't have an option for naming an output file because they don't need one.
Instead,
you can use <strong>redirection</strong> to save any command's output anywhere you want.
If you run this command:</p>
<pre><code>head -n 5 seasonal/summer.csv
</code></pre>
<p>it prints the first 5 lines of the summer data on the screen.
If you run this command instead:</p>
<pre><code>head -n 5 seasonal/summer.csv &gt; top.csv
</code></pre>
<p>nothing appears on the screen.
Instead,
<code>head</code>'s output is put in a new file called <code>top.csv</code>.
You can take a look at that file's contents using <code>cat</code>:</p>
<pre><code>cat top.csv
</code></pre>
<p>The greater-than sign <code>&gt;</code> tells the shell to redirect <code>head</code>'s output to a file.
It isn't part of the <code>head</code> command;
instead,
it works with every shell command that produces output.</p>
</div>
<div class="exercise--instructions__content"><p>Combine <code>tail</code> with redirection to save the last 5 lines of <code>seasonal/winter.csv</code> in a file called <code>last.csv</code>.</p></div>
```{sh,eval=F}
tail -n 5 seasonal/winter.csv > last.csv

```

<p class="">Nice! Let's practice some more!</p>

#### Command's output as an input? {.unnumbered}


<div class>
<p>Suppose you want to get lines from the middle of a file.
More specifically,
suppose you want to get lines 3-5 from one of our data files.
You can start by using <code>head</code> to get the first 5 lines
and redirect that to a file,
and then use <code>tail</code> to select the last 3:</p>
<pre><code>head -n 5 seasonal/winter.csv &gt; top.csv
tail -n 3 top.csv
</code></pre>
<p>A quick check confirms that this is lines 3-5 of our original file,
because it is the last 3 lines of the first 5.</p>
</div>
<div class="exercise--instructions__content"><p>Select the last two lines from <code>seasonal/winter.csv</code>
and save them in a file called <code>bottom.csv</code>.</p></div>
```{sh,eval=F}
tail -n 2 seasonal/winter.csv > bottom.csv

```

<div class="exercise--instructions__content"><p>Select the first line from <code>bottom.csv</code>
in order to get the second-to-last line of the original file.</p></div>
```{sh,eval=F}
head -n 1 bottom.csv

```

<p class="">Well done. Head over to the next exercise to find out about better ways to combine commands.</p>

#### Better way to combine commands? {.unnumbered}


<div class>
<p>Using redirection to combine commands has two drawbacks:</p>
<ol>
<li>It leaves a lot of intermediate files lying around (like <code>top.csv</code>).</li>
<li>The commands to produce your final result are scattered across several lines of history.</li>
</ol>
<p>The shell provides another tool that solves both of these problems at once called a <strong>pipe</strong>.
Once again,
start by running <code>head</code>:</p>
<pre><code>head -n 5 seasonal/summer.csv
</code></pre>
<p>Instead of sending <code>head</code>'s output to a file,
add a vertical bar and the <code>tail</code> command <em>without</em> a filename:</p>
<pre><code>head -n 5 seasonal/summer.csv | tail -n 3
</code></pre>
<p>The pipe symbol tells the shell to use the output of the command on the left
as the input to the command on the right.</p>
</div>
<div class="exercise--instructions__content"><p>Use <code>cut</code> to select all of the tooth names from column 2 of the comma delimited file <code>seasonal/summer.csv</code>, then pipe the result to <code>grep</code>, with an inverted match, to exclude the header line containing the word "Tooth". <em><code>cut</code> and <code>grep</code> were covered in detail in Chapter 2, exercises 8 and 11 respectively.</em></p></div>
```{sh,eval=F}
cut -d , -f 2 seasonal/summer.csv | grep -v Tooth

```

<p class="">Perfect piping! This may be the first time you used <code>|</code>, but it's definitely not the last!</p>

#### Combine many commands? {.unnumbered}


<div class>
<p>You can chain any number of commands together.
For example,
this command:</p>
<pre><code>cut -d , -f 1 seasonal/spring.csv | grep -v Date | head -n 10
</code></pre>
<p>will:</p>
<ol>
<li>select the first column from the spring data;</li>
<li>remove the header line containing the word "Date"; and</li>
<li>select the first 10 lines of actual data.</li>
</ol>
</div>
<div class="exercise--instructions__content">
<p>In the previous exercise, you used the following command to select all the tooth names from column 2 of <code>seasonal/summer.csv</code>:</p>
<pre><code>cut -d , -f 2 seasonal/summer.csv | grep -v Tooth
</code></pre>
<p>Extend this pipeline with a <code>head</code> command to only select the very first tooth name.</p>
</div>
```{sh,eval=F}
cut -d , -f 2 seasonal/summer.csv | grep -v Tooth | head -n 1

```

<p class="">Cheerful chaining! By chaining several commands together, you can build powerful data manipulation pipelines.</p>

#### Count the records in a file? {.unnumbered}


<div class><p>The command <code>wc</code> (short for "word count") prints the number of <strong>c</strong>haracters, <strong>w</strong>ords, and <strong>l</strong>ines in a file.
You can make it print only one of these using <code>-c</code>, <code>-w</code>, or <code>-l</code> respectively.</p></div>
<div class="exercise--instructions__content">
<p>Count how many records in <code>seasonal/spring.csv</code> have dates in July 2017 (<code>2017-07</code>). </p>
<ul>
<li>To do this, use <code>grep</code> with a partial date to select the lines and pipe this result into <code>wc</code> with an appropriate flag to count the lines.</li>
</ul>
</div>

```{sh,eval=F}
grep 2017-07 seasonal/spring.csv | wc -l

```

<p class="">Careful counting! Determining how much data you have is a great first step in any data analysis.</p>

#### Specify many files at once? {.unnumbered}


<div class>
<p>Most shell commands will work on multiple files if you give them multiple filenames.
For example,
you can get the first column from all of the seasonal data files at once like this:</p>
<pre><code>cut -d , -f 1 seasonal/winter.csv seasonal/spring.csv seasonal/summer.csv seasonal/autumn.csv
</code></pre>
<p>But typing the names of many files over and over is a bad idea:
it wastes time,
and sooner or later you will either leave a file out or repeat a file's name.
To make your life better,
the shell allows you to use <strong>wildcards</strong> to specify a list of files with a single expression.
The most common wildcard is <code>*</code>,
which means "match zero or more characters".
Using it,
we can shorten the <code>cut</code> command above to this:</p>
<pre><code>cut -d , -f 1 seasonal/*
</code></pre>
<p>or:</p>
<pre><code>cut -d , -f 1 seasonal/*.csv
</code></pre>
</div>
<div class="exercise--instructions__content"><p>Write a single command using <code>head</code> to get the first three lines from both <code>seasonal/spring.csv</code> and <code>seasonal/summer.csv</code>, a total of six lines of data, but <em>not</em> from the autumn or winter data files.
Use a wildcard instead of spelling out the files' names in full.</p></div>
```{sh,eval=F}
head -n 3 seasonal/s* # ...or seasonal/s*.csv, or even s*/s*.csv

```

<p class="">Wild wildcard work! This becomes even more important if your directory contains hundreds or thousands of files.</p>

#### Other wildcards {.unnumbered}

<div class=""><p>The shell has other wildcards as well,
though they are less commonly used:</p>
<ul>
<li><code>?</code> matches a single character, so <code>201?.txt</code> will match <code>2017.txt</code> or <code>2018.txt</code>, but not <code>2017-01.txt</code>.</li>
<li><code>[...]</code> matches any one of the characters inside the square brackets, so <code>201[78].txt</code> matches <code>2017.txt</code> or <code>2018.txt</code>, but not <code>2016.txt</code>.</li>
<li><code>{...}</code> matches any of the comma-separated patterns inside the curly brackets, so <code>{*.txt, *.csv}</code> matches any file whose name ends with <code>.txt</code> or <code>.csv</code>, but not files whose names end with <code>.pdf</code>.</li>
</ul>
<hr>
<p>Which expression would match <code>singh.pdf</code> and <code>johel.txt</code> but <em>not</em> <code>sandhu.pdf</code> or <code>sandhu.txt</code>?</p></div>

- [ ] <code>[sj]*.{.pdf, .txt}</code>
- [ ] <code>{s*.pdf, j*.txt}</code>
- [ ] <code>[singh,johel]{*.pdf, *.txt}</code>
- [x] <code>{singh.pdf, j*.txt}</code>

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct!</p>

#### Sort lines of text? {.unnumbered}


<div class><p>As its name suggests,
<code>sort</code> puts data in order.
By default it does this in ascending alphabetical order,
but the flags <code>-n</code> and <code>-r</code> can be used to sort numerically and reverse the order of its output,
while <code>-b</code> tells it to ignore leading blanks
and <code>-f</code> tells it to <strong>f</strong>old case (i.e., be case-insensitive).
Pipelines often use <code>grep</code> to get rid of unwanted records
and then <code>sort</code> to put the remaining records in order.</p></div>
<div class="exercise--instructions__content">
<p>Remember the combination of <code>cut</code> and <code>grep</code> to select all the tooth names from column 2 of <code>seasonal/summer.csv</code>?</p>
<pre><code>cut -d , -f 2 seasonal/summer.csv | grep -v Tooth
</code></pre>
<p>Starting from this recipe, sort the names of the teeth in <code>seasonal/winter.csv</code> (not <code>summer.csv</code>) in descending alphabetical order. To do this, extend the pipeline with a <code>sort</code> step.</p>
</div>
```{sh,eval=F}
cut -d , -f 2 seasonal/winter.csv | grep -v Tooth | sort -r

```

<p class="">Sorted! <code>sort</code> has many uses. For example, piping <code>sort -n</code> to <code>head</code> shows you the largest values.</p>

#### Remove duplicate lines? {.unnumbered}


<div class>
<p>Another command that is often used with <code>sort</code> is <code>uniq</code>,
whose job is to remove duplicated lines.
More specifically,
it removes <em>adjacent</em> duplicated lines.
If a file contains:</p>
<pre><code>2017-07-03
2017-07-03
2017-08-03
2017-08-03
</code></pre>
<p>then <code>uniq</code> will produce:</p>
<pre><code>2017-07-03
2017-08-03
</code></pre>
<p>but if it contains:</p>
<pre><code>2017-07-03
2017-08-03
2017-07-03
2017-08-03
</code></pre>
<p>then <code>uniq</code> will print all four lines.
The reason is that <code>uniq</code> is built to work with very large files.
In order to remove non-adjacent lines from a file,
it would have to keep the whole file in memory
(or at least,
all the unique lines seen so far).
By only removing adjacent duplicates,
it only has to keep the most recent unique line in memory.</p>
</div>
<div class="exercise--instructions__content">
<p>Write a pipeline to:</p>
<ul>
<li>get the second column from <code>seasonal/winter.csv</code>,</li>
<li>remove the word "Tooth" from the output so that only tooth names are displayed,</li>
<li>sort the output so that all occurrences of a particular tooth name are adjacent; and</li>
<li>display each tooth name once along with a count of how often it occurs.</li>
</ul>
<p>The start of your pipeline is the same as the previous exercise:</p>
<pre><code>cut -d , -f 2 seasonal/winter.csv | grep -v Tooth
</code></pre>
<p>Extend it with a <code>sort</code> command, and use <code>uniq -c</code> to display unique lines with a count of how often each occurs rather than using <code>uniq</code> and <code>wc</code>.</p>
</div>
```{sh,eval=F}
cut -d , -f 2 seasonal/winter.csv | grep -v Tooth | sort | uniq -c

```

<p class="">Great! After all of this work on a pipe, it would be nice if we could store the result, no?</p>

#### Save the output of a pipe? {.unnumbered}


<div class>
<p>The shell lets us redirect the output of a sequence of piped commands:</p>
<pre><code>cut -d , -f 2 seasonal/*.csv | grep -v Tooth &gt; teeth-only.txt
</code></pre>
<p>However, <code>&gt;</code> must appear at the end of the pipeline:
if we try to use it in the middle, like this:</p>
<pre><code>cut -d , -f 2 seasonal/*.csv &gt; teeth-only.txt | grep -v Tooth
</code></pre>
<p>then all of the output from <code>cut</code> is written to <code>teeth-only.txt</code>,
so there is nothing left for <code>grep</code>
and it waits forever for some input.</p>
<hr>
<p>What happens if we put redirection at the front of a pipeline as in:</p>
<pre><code>&gt; result.txt head -n 3 seasonal/winter.csv
</code></pre>
</div>

- [ ] The command's output is redirected to the file as usual.
- [ ] The shell reports it as an error.
- [ ] The shell waits for input forever.

<p class="">Correct!</p>

#### Stop a running program? {.unnumbered}


<div class><p>The commands and scripts that you have run so far have all executed quickly,
but some tasks will take minutes, hours, or even days to complete.
You may also mistakenly put redirection in the middle of a pipeline,
causing it to hang up.
If you decide that you don't want a program to keep running,
you can type <code>Ctrl</code> + <code>C</code> to end it.
This is often written <code>^C</code> in Unix documentation;
note that the 'c' can be lower-case.</p></div>
<div class="exercise--instructions__content">
<p>Run the command:</p>
<pre><code>head
</code></pre>
<p>with no arguments (so that it waits for input that will never come)
and then stop it by typing <code>Ctrl</code> + <code>C</code>.</p>
</div>

```{sh,eval=F}
# Simply type head, hit Enter and exit the running program with `Ctrl` + `C`.
```

<p class="">Great work!</p>

#### Wrapping up {.unnumbered}


<div class><p>To wrap up,
you will build a pipeline to find out how many records are in the shortest of the seasonal data files.</p></div>
<div class="exercise--instructions__content"><p>Use <code>wc</code> with appropriate parameters to list the number of lines in all of the seasonal data files.
(Use a wildcard for the filenames instead of typing them all in by hand.)</p></div>
```{sh,eval=F}
wc -l seasonal/*.csv


```
<div class="exercise--instructions__content"><p>Add another command to the previous one using a pipe to remove the line containing the word "total".</p></div>
```{sh,eval=F}
wc -l seasonal/*.csv | grep -v total

```


<div class="exercise--instructions__content"><p>Add two more stages to the pipeline that use <code>sort -n</code> and <code>head -n 1</code> to find the file containing the fewest lines.</p></div>
```{sh,eval=F}
wc -l seasonal/*.csv | grep -v total | sort -n | head -n 1

```

<p class="">Great! It turns out <code>autumn.csv</code> is the file with the fewest lines. Rush over to chapter 4 to learn more about batch processing!</p>

### Batch processing {.unnumbered}

Most shell commands will process many files at once. This chapter shows you how to make your own pipelines do that. Along the way, you will see how the shell uses variables to store information.

#### Shell store information? {.unnumbered}


<div class>
<p>Like other programs, the shell stores information in variables.
Some of these,
called <strong>environment variables</strong>,
are available all the time.
Environment variables' names are conventionally written in upper case,
and a few of the more commonly-used ones are shown below.</p>
<table>
<thead><tr>
<th>Variable</th>
<th>Purpose</th>
<th>Value</th>
</tr></thead>
<tbody>
<tr>
<td><code>HOME</code></td>
<td>User's home directory</td>
<td><code>/home/repl</code></td>
</tr>
<tr>
<td><code>PWD</code></td>
<td>Present working directory</td>
<td>Same as <code>pwd</code> command</td>
</tr>
<tr>
<td><code>SHELL</code></td>
<td>Which shell program is being used</td>
<td><code>/bin/bash</code></td>
</tr>
<tr>
<td><code>USER</code></td>
<td>User's ID</td>
<td><code>repl</code></td>
</tr>
</tbody>
</table>
<p>To get a complete list (which is quite long),
you can type <code>set</code> in the shell.</p>
<hr>
<p>Use <code>set</code> and <code>grep</code> with a pipe to display the value of <code>HISTFILESIZE</code>,
which determines how many old commands are stored in your command history.
What is its value?</p>
</div>

- [ ] 10
- [ ] 500
- [x] 2000
- [ ] The variable is not there.

<p class="">Correct: the shell saves 2000 old commands by default on this system.</p>

#### Print a variable's value? {.unnumbered}


<div class>
<p>A simpler way to find a variable's value is to use a command called <code>echo</code>, which prints its arguments. Typing</p>
<pre><code>echo hello DataCamp!
</code></pre>
<p>prints</p>
<pre><code>hello DataCamp!
</code></pre>
<p>If you try to use it to print a variable's value like this:</p>
<pre><code>echo USER
</code></pre>
<p>it will print the variable's name, <code>USER</code>.</p>
<p>To get the variable's value, you must put a dollar sign <code>$</code> in front of it. Typing </p>
<pre><code>echo $USER
</code></pre>
<p>prints</p>
<pre><code>repl
</code></pre>
<p>This is true everywhere:
to get the value of a variable called <code>X</code>,
you must write <code>$X</code>.
(This is so that the shell can tell whether you mean "a file named X"
or "the value of a variable named X".)</p>
</div>
<div class="exercise--instructions__content"><p>The variable <code>OSTYPE</code> holds the name of the kind of operating system you are using.
Display its value using <code>echo</code>.</p></div>
```{sh,eval=F}
echo $OSTYPE

```

<p class="">Excellent echoing of environment variables! You're off to a good start. Let's carry on!</p>

#### Shell store information? {.unnumbered}


<div class>
<p>The other kind of variable is called a <strong>shell variable</strong>,
which is like a local variable in a programming language.</p>
<p>To create a shell variable,
you simply assign a value to a name:</p>
<pre><code>training=seasonal/summer.csv
</code></pre>
<p><em>without</em> any spaces before or after the <code>=</code> sign.
Once you have done this,
you can check the variable's value with:</p>
<pre><code>echo $training
</code></pre>
<pre><code>seasonal/summer.csv
</code></pre>
</div>
<div class="exercise--instructions__content"><p>Define a variable called <code>testing</code> with the value <code>seasonal/winter.csv</code>.</p></div>
```{sh,eval=F}
testing=seasonal/winter.csv

```

<div class="exercise--instructions__content"><p>Use <code>head -n 1 SOMETHING</code> to get the first line from <code>seasonal/winter.csv</code>
using the value of the variable <code>testing</code> instead of the name of the file.</p></div>
```{sh,eval=F}
# We need to re-set the variable for testing purposes for this exercise
# you should only run "head -n 1 $testing"
testing=seasonal/winter.csv
head -n 1 $testing
```

<p class="">Stellar! Let's see how you can repeat commands easily.</p>

#### Repeat a command {.unnumbered}


<div class>
<p>Shell variables are also used in <strong>loops</strong>,
which repeat commands many times.
If we run this command:</p>
<pre><code>for filetype in gif jpg png; do echo $filetype; done
</code></pre>
<p>it produces:</p>
<pre><code>gif
jpg
png
</code></pre>
<p>Notice these things about the loop:</p>
<ol>
<li>The structure is <code>for</code> …variable… <code>in</code> …list… <code>; do</code> …body… <code>; done</code>
</li>
<li>The list of things the loop is to process (in our case, the words <code>gif</code>, <code>jpg</code>, and <code>png</code>).</li>
<li>The variable that keeps track of which thing the loop is currently processing (in our case, <code>filetype</code>).</li>
<li>The body of the loop that does the processing (in our case, <code>echo $filetype</code>).</li>
</ol>
<p>Notice that the body uses <code>$filetype</code> to get the variable's value instead of just <code>filetype</code>,
just like it does with any other shell variable.
Also notice where the semi-colons go:
the first one comes between the list and the keyword <code>do</code>,
and the second comes between the body and the keyword <code>done</code>.</p>
</div>
<div class="exercise--instructions__content">
<p>Modify the loop so that it prints:</p>
<pre><code>docx
odt
pdf
</code></pre>
<p>Please use <code>filetype</code> as the name of the loop variable.</p>
</div>
```{sh,eval=F}
for filetype in docx odt pdf; do echo $filetype; done

```

<p class="">First-rate for looping! Loops are brilliant if you want to do the same thing hundreds or thousands of times.</p>

#### Repeat command for file {.unnumbered}


<div class>
<p>You can always type in the names of the files you want to process when writing the loop,
but it's usually better to use wildcards.
Try running this loop in the console:</p>
<pre><code>for filename in seasonal/*.csv; do echo $filename; done
</code></pre>
<p>It prints:</p>
<pre><code>seasonal/autumn.csv
seasonal/spring.csv
seasonal/summer.csv
seasonal/winter.csv
</code></pre>
<p>because the shell expands <code>seasonal/*.csv</code> to be a list of four filenames
before it runs the loop.</p>
</div>
<div class="exercise--instructions__content"><p>Modify the wildcard expression to <code>people/*</code>
so that the loop prints the names of the files in the <code>people</code> directory
regardless of what suffix they do or don't have.
Please use <code>filename</code> as the name of your loop variable.</p></div>
```{sh,eval=F}
for filename in people/*; do echo $filename; done

```

<p class="">Loopy looping! Wildcards and loops make a powerful combination.</p>

#### Record the names of files? {.unnumbered}


<div class>
<p>People often set a variable using a wildcard expression to record a list of filenames.
For example,
if you define <code>datasets</code> like this:</p>
<pre><code>datasets=seasonal/*.csv
</code></pre>
<p>you can display the files' names later using:</p>
<pre><code>for filename in $datasets; do echo $filename; done
</code></pre>
<p>This saves typing and makes errors less likely.</p>
<hr>
<p>If you run these two commands in your home directory,
how many lines of output will they print?</p>
<pre><code>files=seasonal/*.csv
for f in $files; do echo $f; done
</code></pre>
</div>

- [ ] None: since <code>files</code> is defined on a separate line, it has no value in the second line.
- [ ] One: the word "files".
- [ ] Four: the names of all four seasonal data files.

<p class="">Correct. The command is equivalent to <code>for f in seasonal/*.csv; do echo $f; done</code>.</p>

#### Variable's name & value {.unnumbered}

<div class=""><p>A common mistake is to forget to use <code>$</code> before the name of a variable.
When you do this,
the shell uses the name you have typed
rather than the value of that variable.</p>
<p>A more common mistake for experienced users is to mis-type the variable's name.
For example,
if you define <code>datasets</code> like this:</p>
<pre><code>datasets=seasonal/*.csv
</code></pre>
<p>and then type:</p>
<pre><code>echo $datsets
</code></pre>
<p>the shell doesn't print anything,
because <code>datsets</code> (without the second "a") isn't defined.</p>
<hr>
<p>If you were to run these two commands in your home directory,
what output would be printed?</p>
<pre><code>files=seasonal/*.csv
for f in files; do echo $f; done
</code></pre>
<p>(Read the first part of the loop carefully before answering.)</p></div>

- [x] One line: the word "files".
- [ ] Four lines: the names of all four seasonal data files.
- [ ] Four blank lines: the variable <code>f</code> isn't assigned a value.

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct: the loop uses <code>files</code> instead of <code>$files</code>, so the list consists of the word "files".</p>

#### Commands in a single loop {.unnumbered}


<div class>
<p>Printing filenames is useful for debugging,
but the real purpose of loops is to do things with multiple files.
This loop prints the second line of each data file:</p>
<pre><code>for file in seasonal/*.csv; do head -n 2 $file | tail -n 1; done
</code></pre>
<p>It has the same structure as the other loops you have already seen:
all that's different is that its body is a pipeline of two commands instead of a single command.</p>
</div>
<div class="exercise--instructions__content">
<p>Write a loop that prints the last entry from July 2017 (<code>2017-07</code>) in every seasonal file. It should produce a similar output to:</p>
<pre><code>grep 2017-07 seasonal/winter.csv | tail -n 1
</code></pre>
<p>but for <strong><em>each</em></strong> seasonal file separately. Please use <code>file</code> as the name of the loop variable, and remember to loop through the list of files <code>seasonal/*.csv</code> (<em>instead of 'seasonal/winter.csv' as in the example</em>).</p>
</div>
```{sh,eval=F}
for file in seasonal/*.csv; do grep 2017-07 $file | tail -n 1; done

```

<p class="">Loopy looping! Wildcards and loops make a powerful combination.</p>

#### Spaces in filenames! {.unnumbered}

<div class=""><p>It's easy and sensible to give files multi-word names like <code>July 2017.csv</code>
when you are using a graphical file explorer.
However,
this causes problems when you are working in the shell.
For example,
suppose you wanted to rename <code>July 2017.csv</code> to be <code>2017 July data.csv</code>.
You cannot type:</p>
<pre><code>mv July 2017.csv 2017 July data.csv
</code></pre>
<p>because it looks to the shell as though you are trying to move
four files called <code>July</code>, <code>2017.csv</code>, <code>2017</code>, and <code>July</code> (again)
into a directory called <code>data.csv</code>.
Instead,
you have to quote the files' names
so that the shell treats each one as a single parameter:</p>
<pre><code>mv 'July 2017.csv' '2017 July data.csv'
</code></pre>
<hr>
<p>If you have two files called <code>current.csv</code> and <code>last year.csv</code>
(with a space in its name)
and you type:</p>
<pre><code>rm current.csv last year.csv
</code></pre>
<p>what will happen:</p></div>

- [ ] The shell will print an error message because <code>last</code> and <code>year.csv</code> do not exist.
- [ ] The shell will delete <code>current.csv</code>.
- [x] Both of the above.
- [ ] Nothing.

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct. You can use single quotes, <code>'</code>, or double quotes, <code>"</code>, around the file names.</p>

#### Things in a single loop {.unnumbered}


<div class>
<p>The loops you have seen so far all have a single command or pipeline in their body,
but a loop can contain any number of commands.
To tell the shell where one ends and the next begins,
you must separate them with semi-colons:</p>
<pre><code>for f in seasonal/*.csv; do echo $f; head -n 2 $f | tail -n 1; done
</code></pre>
<pre><code>seasonal/autumn.csv
2017-01-05,canine
seasonal/spring.csv
2017-01-25,wisdom
seasonal/summer.csv
2017-01-11,canine
seasonal/winter.csv
2017-01-03,bicuspid
</code></pre>
<hr>
<p>Suppose you forget the semi-colon between the <code>echo</code> and <code>head</code> commands in the previous loop,
so that you ask the shell to run:</p>
<pre><code>for f in seasonal/*.csv; do echo $f head -n 2 $f | tail -n 1; done
</code></pre>
<p>What will the shell do?</p>
</div>

- [ ] Print an error message.
- [x] Print one line for each of the four files.
- [ ] Print one line for <code>autumn.csv</code> (the first file).
- [ ] Print the last line of each file.

<p class="">Yes: <code>echo</code> produces one line that includes the filename twice, which <code>tail</code> then copies.</p>

#### Edit a file? {.unnumbered}


<div class>
<p>Unix has a bewildering variety of text editors.
For this course,
we will use a simple one called Nano.
If you type <code>nano filename</code>,
it will open <code>filename</code> for editing
(or create it if it doesn't already exist).
You can move around with the arrow keys,
delete characters using backspace,
and do other operations with control-key combinations:</p>
<ul>
<li>
<code>Ctrl</code> + <code>K</code>: delete a line.</li>
<li>
<code>Ctrl</code> + <code>U</code>: un-delete a line.</li>
<li>
<code>Ctrl</code> + <code>O</code>: save the file ('O' stands for 'output'). <em>You will also need to press Enter to confirm the filename!</em>
</li>
<li>
<code>Ctrl</code> + <code>X</code>: exit the editor.</li>
</ul>
</div>
<div class="exercise--instructions__content">
<p>Run <code>nano names.txt</code> to edit a new file in your home directory
and enter the following four lines:</p>
<pre><code>Lovelace
Hopper
Johnson
Wilson
</code></pre>
<p>To save what you have written,
type <code>Ctrl</code> + <code>O</code> to write the file out,
then Enter to confirm the filename,
then <code>Ctrl</code> + <code>X</code> to exit the editor.</p>
</div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/names.txt /home/repl
```

Well done! Off to the next one!



#### Record what I just did? {.unnumbered}


<div class>
<p>When you are doing a complex analysis,
you will often want to keep a record of the commands you used.
You can do this with the tools you have already seen:</p>
<ol>
<li>Run <code>history</code>.</li>
<li>Pipe its output to <code>tail -n 10</code> (or however many recent steps you want to save).</li>
<li>Redirect that to a file called something like <code>figure-5.history</code>.</li>
</ol>
<p>This is better than writing things down in a lab notebook
because it is guaranteed not to miss any steps.
It also illustrates the central idea of the shell:
simple tools that produce and consume lines of text
can be combined in a wide variety of ways
to solve a broad range of problems.</p>
</div>
<div class="exercise--instructions__content"><p>Copy the files <code>seasonal/spring.csv</code> and <code>seasonal/summer.csv</code> to your home directory.</p></div>
```{sh,eval=F}
cp seasonal/s* ~

```

<div class="exercise--instructions__content"><p>Use <code>grep</code> with the <code>-h</code> flag (to stop it from printing filenames)
and <code>-v Tooth</code> (to select lines that <em>don't</em> match the header line)
to select the data records from <code>spring.csv</code> and <code>summer.csv</code> in that order
and redirect the output to <code>temp.csv</code>.</p></div>
```{sh,eval=F}
grep -h -v Tooth spring.csv summer.csv > temp.csv

```
<div class="exercise--instructions__content"><p>Pipe <code>history</code> into <code>tail -n 3</code>
and redirect the output to <code>steps.txt</code>
to save the last three commands in a file.
(You need to save three instead of just two
because the <code>history</code> command itself will be in the list.)</p></div>
```{sh,eval=F}
history | tail -n 3 > steps.txt

```

<p class="">Well done! Let's step it up!</p>

#### Re-run save commands {.unnumbered}


<div class>
<p>You have been using the shell interactively so far.
But since the commands you type in are just text,
you can store them in files for the shell to run over and over again.
To start exploring this powerful capability,
put the following command in a file called <code>headers.sh</code>:</p>
<pre><code>head -n 1 seasonal/*.csv
</code></pre>
<p>This command selects the first row from each of the CSV files in the <code>seasonal</code> directory.
Once you have created this file,
you can run it by typing:</p>
<pre><code>bash headers.sh
</code></pre>
<p>This tells the shell (which is just a program called <code>bash</code>)
to run the commands contained in the file <code>headers.sh</code>,
which produces the same output as running the commands directly.</p>
</div>
<div class="exercise--instructions__content">
<p>Use <code>nano dates.sh</code> to create a file called <code>dates.sh</code>
that contains this command:</p>
<pre><code>cut -d , -f 1 seasonal/*.csv
</code></pre>
<p>to extract the first column from all of the CSV files in <code>seasonal</code>.</p>
</div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/dates.sh ~
```

<div class="exercise--instructions__content"><p>Use <code>bash</code> to run the file <code>dates.sh</code>.</p></div>
```{sh,eval=F}
bash dates.sh

```

<p class="">Great work!</p>

#### Re-use pipes? {.unnumbered}


<div class>
<p>A file full of shell commands is called a <strong>*shell script</strong>,
or sometimes just a "script" for short. Scripts don't have to have names ending in <code>.sh</code>,
but this lesson will use that convention
to help you keep track of which files are scripts.</p>
<p>Scripts can also contain pipes.
For example,
if <code>all-dates.sh</code> contains this line:</p>
<pre><code>cut -d , -f 1 seasonal/*.csv | grep -v Date | sort | uniq
</code></pre>
<p>then:</p>
<pre><code>bash all-dates.sh &gt; dates.out
</code></pre>
<p>will extract the unique dates from the seasonal data files
and save them in <code>dates.out</code>.</p>
</div>
<div class="exercise--instructions__content"><p>A file <code>teeth.sh</code> in your home directory has been prepared for you, but contains some blanks.
Use Nano to edit the file and replace the two <code>____</code> placeholders
with <code>seasonal/*.csv</code> and <code>-c</code> so that this script prints a count of the
number of times each tooth name appears in the CSV files in the <code>seasonal</code> directory.</p></div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/teeth.sh ~
```

<div class="exercise--instructions__content"><p>Use <code>bash</code> to run <code>teeth.sh</code> and <code>&gt;</code> to redirect its output to <code>teeth.out</code>.</p></div>
```{sh,eval=F}
# We need to use 'cp' below to satisfy our automated tests.
# You should only use the last line that runs 'bash'.
cp /solutions/teeth.sh .
bash teeth.sh > teeth.out
```

<div class="exercise--instructions__content"><p>Run <code>cat teeth.out</code> to inspect your results.</p></div>
```{sh,eval=F}
cat teeth.out

```

<p class="">Nice! This all may feel contrived at first, but the nice thing is that you are automating parts of your workflow step by step. Something that comes in really handy as a data scientist!</p>

#### Pass filenames to scripts? {.unnumbered}


<div class>
<p>A script that processes specific files is useful as a record of what you did, but one that allows you to process any files you want is more useful.
To support this,
you can use the special expression <code><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="0d294d">[email.protected]</a></code> (dollar sign immediately followed by at-sign)
to mean "all of the command-line parameters given to the script".</p>
<p>For example, if <code>unique-lines.sh</code> contains <code>sort <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="b195f1">[email.protected]</a> | uniq</code>, when you run:</p>
<pre><code>bash unique-lines.sh seasonal/summer.csv
</code></pre>
<p>the shell replaces <code><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="173357">[email.protected]</a></code> with <code>seasonal/summer.csv</code> and processes one file. If you run this:</p>
<pre><code>bash unique-lines.sh seasonal/summer.csv seasonal/autumn.csv
</code></pre>
<p>it processes two data files, and so on.</p>
<p><em>As a reminder, to save what you have written in Nano, type <code>Ctrl</code> + <code>O</code> to write the file out, then Enter to confirm the filename, then <code>Ctrl</code> + <code>X</code> to exit the editor.</em></p>
</div>
<div class="exercise--instructions__content"><p>Edit the script <code>count-records.sh</code> with Nano and fill in the two <code>____</code> placeholders
with <code><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="92b6d2">[email.protected]</a></code> and <code>-l</code> (<em>the letter</em>) respectively so that it counts the number of lines in one or more files,
excluding the first line of each.</p></div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/count-records.sh ~
```

<div class="exercise--instructions__content"><p>Run <code>count-records.sh</code> on <code>seasonal/*.csv</code>
and redirect the output to <code>num-records.out</code> using <code>&gt;</code>.</p></div>
```{sh,eval=F}
bash count-records.sh seasonal/*.csv > num-records.out

```

<p class="">A job well done! Your shell power is ever-expanding!</p>

#### Process a single argument? {.unnumbered}

<div class=""><p>As well as <code>$@</code>,
the shell lets you use <code>$1</code>, <code>$2</code>, and so on to refer to specific command-line parameters.
You can use this to write commands that feel simpler or more natural than the shell's.
For example,
you can create a script called <code>column.sh</code> that selects a single column from a CSV file
when the user provides the filename as the first parameter and the column as the second:</p>
<pre><code>cut -d , -f $2 $1
</code></pre>
<p>and then run it using:</p>
<pre><code>bash column.sh seasonal/autumn.csv 1
</code></pre>
<p>Notice how the script uses the two parameters in reverse order.</p>
<hr>
<p>The script <code>get-field.sh</code> is supposed to take a filename,
the number of the row to select,
the number of the column to select,
and print just that field from a CSV file.
For example:</p>
<pre><code>bash get-field.sh seasonal/summer.csv 4 2
</code></pre>
<p>should select the second field from line 4 of <code>seasonal/summer.csv</code>.
Which of the following commands should be put in <code>get-field.sh</code> to do that?</p></div>

- [ ] <code>head -n $1 $2 | tail -n 1 | cut -d , -f $3</code>
- [x] <code>head -n $2 $1 | tail -n 1 | cut -d , -f $3</code>
- [ ] <code>head -n $3 $1 | tail -n 1 | cut -d , -f $2</code>
- [ ] <code>head -n $2 $3 | tail -n 1 | cut -d , -f $1</code>

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct!</p>

#### Shell script do many things {.unnumbered}


<div class>
<p>Our shells scripts so far have had a single command or pipe, but a script can contain many lines of commands. For example, you can create one that tells you how many records are in the shortest and longest of your data files, i.e., the range of your datasets' lengths.</p>
<p>Note that in Nano, "copy and paste" is achieved by navigating to the line you want to copy, pressing <code>CTRL</code> + <code>K</code> to cut the line, then <code>CTRL</code> + <code>U</code> twice to paste two copies of it.</p>
<p><em>As a reminder, to save what you have written in Nano, type <code>Ctrl</code> + <code>O</code> to write the file out, then Enter to confirm the filename, then <code>Ctrl</code> + <code>X</code> to exit the editor.</em></p>
</div>
<div class="exercise--instructions__content"><p>Use Nano to edit the script <code>range.sh</code>
and replace the two <code>____</code> placeholders
with <code><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="f6d2b6">[email.protected]</a></code> and <code>-v</code>
so that it lists the names and number of lines in all of the files given on the command line
<em>without</em> showing the total number of lines in all files.
(Do not try to subtract the column header lines from the files.)</p></div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/range-1.sh range.sh
```

<div class="exercise--instructions__content"><p>Use Nano again to add <code>sort -n</code> and <code>head -n 1</code> in that order
to the pipeline in <code>range.sh</code>
to display the name and line count of the shortest file given to it.</p></div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/range-2.sh range.sh
```
<div class="exercise--instructions__content"><p>Again using Nano, add a second line to <code>range.sh</code> to print the name and record count of
the <em>longest</em> file in the directory <em>as well as</em> the shortest.
This line should be a duplicate of the one you have already written,
but with <code>sort -n -r</code> rather than <code>sort -n</code>.</p></div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/range-3.sh range.sh
```
<div class="exercise--instructions__content"><p>Run the script on the files in the <code>seasonal</code> directory
using <code>seasonal/*.csv</code> to match all of the files
and redirect the output using <code>&gt;</code>
to a file called <code>range.out</code> in your home directory.</p></div>
```{sh,eval=F}
bash range.sh seasonal/*.csv > range.out
```

<p class="">This is going well. Head over to the next exercise to learn about writing loops!</p>

#### Write loops in a shell script? {.unnumbered}


<div class>
<p>Shell scripts can also contain loops. You can write them using semi-colons, or split them across lines without semi-colons to make them more readable:</p>
<pre><code># Print the first and last data records of each file.
for filename in <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="341074">[email.protected]</a>
do
    head -n 2 $filename | tail -n 1
    tail -n 1 $filename
done
</code></pre>
<p>(You don't have to indent the commands inside the loop, but doing so makes things clearer.)</p>
<p>The first line of this script is a <strong>comment</strong> to tell readers what the script does. Comments start with the <code>#</code> character and run to the end of the line. Your future self will thank you for adding brief explanations like the one shown here to every script you write.</p>
<p><em>As a reminder, to save what you have written in Nano, type <code>Ctrl</code> + <code>O</code> to write the file out, then Enter to confirm the filename, then <code>Ctrl</code> + <code>X</code> to exit the editor.</em></p>
</div>
<div class="exercise--instructions__content"><p>Fill in the placeholders in the script <code>date-range.sh</code>
with <code>$filename</code> (twice), <code>head</code>, and <code>tail</code>
so that it prints the first and last date from one or more files.</p></div>
```{sh,eval=F}
# This solution uses `cp` instead of `nano`
# because our automated tests can't edit files interactively.
cp /solutions/date-range.sh date-range.sh
```

<div class="exercise--instructions__content"><p>Run <code>date-range.sh</code> on all four of the seasonal data files
using <code>seasonal/*.csv</code> to match their names.</p></div>
```{sh,eval=F}
bash date-range.sh seasonal/*.csv
```

<div class="exercise--instructions__content"><p>Run <code>date-range.sh</code> on all four of the seasonal data files using <code>seasonal/*.csv</code> to match their names,
and pipe its output to <code>sort</code> to see that your scripts can be used just like Unix's built-in commands.</p></div>
```{sh,eval=F}
bash date-range.sh seasonal/*.csv | sort
```

<p class="">Magic! Notice how composable all the things we've learned are.</p>

#### What happens when I don't provide filenames? {.unnumbered}


<div class>
<p>A common mistake in shell scripts (and interactive commands) is to put filenames in the wrong place.
If you type:</p>
<pre><code>tail -n 3
</code></pre>
<p>then since <code>tail</code> hasn't been given any filenames,
it waits to read input from your keyboard.
This means that if you type:</p>
<pre><code>head -n 5 | tail -n 3 somefile.txt
</code></pre>
<p>then <code>tail</code> goes ahead and prints the last three lines of <code>somefile.txt</code>,
but <code>head</code> waits forever for keyboard input,
since it wasn't given a filename and there isn't anything ahead of it in the pipeline.</p>
<hr>
<p>Suppose you do accidentally type:</p>
<pre><code>head -n 5 | tail -n 3 somefile.txt
</code></pre>
<p>What should you do next?</p>
</div>

- [ ] Wait 10 seconds for <code>head</code> to time out.
- [ ] Type <code>somefile.txt</code> and press Enter to give <code>head</code> some input.
- [x] Use <code>Ctrl</code> + <code>C</code> to stop the running <code>head</code> program.

<p class="">Yes! You should use <code>Ctrl</code> + <code>C</code> to stop a running program. This concludes this introductory course! If you're interested to learn more command line tools, we thoroughly recommend taking our free intro to Git course!</p>