# Machine Learning {.unnumbered}

## Machine Learning {.unnumbered}

<h3 class="course__description-title">Hugo Bowne-Anderson</h3>
<p class="course__instructor-description display-none-mobile-course-page-experiment">
    Hugo is a data scientist, educator, writer and podcaster formerly at DataCamp. His main interests are promoting data &amp; AI literacy, helping to spread data skills through organizations and society and doing amateur stand up comedy in NYC. If you want to know what he likes to talk about, definitely check out <a href="https://www.datacamp.com/community/podcast">DataFramed</a>, the DataCamp podcast, which he hosted and produced.
  </p>

**Course Description**

<p class="course__description">Machine learning is the field that teaches machines and computers to learn from existing data to make predictions on new data: Will a tumor be benign or malignant? Which of your customers will take their business elsewhere? Is a particular email spam? In this course, you'll learn how to use Python to perform supervised learning, an essential component of machine learning. You'll learn how to build predictive models, tune their parameters, and determine how well they will perform with unseen data—all while using real world datasets. You'll be using scikit-learn, one of the most popular and user-friendly machine learning libraries for Python.</p>

### Classification {.unnumbered}

<p class="chapter__description">
    In this chapter, you will be introduced to classification problems and learn how to solve them using supervised learning techniques. And you’ll apply what you learn to a political dataset, where you classify the party affiliation of United States congressmen based on their voting records.
  </p>
  
#### Supervised learning {.unnumbered}

##### Which of these is a classification problem? {.unnumbered}

<div class=""><p>Once you decide to leverage supervised machine learning to solve a new problem, you need to identify whether your problem
is better suited to classification or regression. This exercise will help you develop your intuition for distinguishing between the two.</p>
<p>Provided below are 4 example applications of machine learning. Which of them is a supervised classification problem?</p></div>

- [x] Using labeled financial data to predict whether the value of a stock will go up or go down next week.
- [ ] Using labeled housing price data to predict the price of a new house based on various features.
- [ ] Using unlabeled data to cluster the students of an online education company into different categories based on their learning styles.
- [ ] Using labeled financial data to predict what the value of a stock will be next week.

<p class="dc-completion-pane__message dc-u-maxw-100pc">Exactly! In this example, there are two discrete, qualitative outcomes: the stock market going up, and the stock market going down. This can be represented using a binary variable, and is an application perfectly suited for classification.</p>

#### Exploratory data analysis {.unnumbered}



##### Numerical EDA {.unnumbered}


<div class>
<p>In this chapter, you'll be working with a dataset obtained from the <a href="https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records">UCI Machine Learning Repository</a> consisting of votes made by US House of Representatives Congressmen. Your goal will be to predict their party affiliation ('Democrat' or 'Republican') based on how they voted on certain key issues. Here, it's worth noting that we have preprocessed this dataset to deal with missing values. This is so that your focus can be directed towards understanding how to train and evaluate supervised learning models. Once you have mastered these fundamentals, you will be introduced to preprocessing techniques in Chapter 4 and have the chance to apply them there yourself - including on this very same dataset!</p>
<p>Before thinking about what supervised learning models you can apply to this, however, you need to perform Exploratory data analysis (EDA) in order to understand the structure of the data. For a refresher on the importance of EDA, check out the first two chapters of <a href="https://www.datacamp.com/courses/statistical-thinking-in-python-part-1">Statistical Thinking in Python (Part 1)</a>. </p>
<p>Get started with your EDA now by exploring this voting records dataset numerically. It has been pre-loaded for you into a DataFrame called <code>df</code>.  Use pandas' <code>.head()</code>, <code>.info()</code>, and <code>.describe()</code> methods in the IPython Shell to explore the DataFrame, and select the statement below that is <strong>not</strong> true.</p>
</div>

```{python}
# edited/added
import pandas as pd
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/votes-ch1.csv')
df.head()
df.info()
df.describe()
```

- [ ] The DataFrame has a total of <code>435</code> rows and <code>17</code> columns.
- [ ] Except for <code>'party'</code>, all of the columns are of type <code>int64</code>.
- [ ] The first two rows of the DataFrame consist of votes made by Republicans and the next three rows consist of votes made by Democrats.
- [x] There are 17 <em>predictor variables</em>, or <em>features</em>, in this DataFrame.
- [ ] The target variable in this DataFrame is <code>'party'</code>.

<p class="">Great work! The number of columns in the DataFrame is not equal to the number of features. One of the columns - <code>'party'</code> is the target variable.</p>

##### Visual EDA {.unnumbered}


<div class>
<p>The Numerical EDA you did in the previous exercise gave you some very important information, such as the names and data types of the columns, and the dimensions of the DataFrame. Following this with some visual EDA will give you an even better understanding of the data. In the video, Hugo used the <code>scatter_matrix()</code> function on the Iris data for this purpose. However, you may have noticed in the previous exercise that all the features in this dataset are binary; that is, they are either 0 or 1. So a different type of plot would be more useful here, such as <a href="http://seaborn.pydata.org/generated/seaborn.countplot.html">Seaborn's <code>countplot</code></a>.</p>
<p>Given on the right is a <code>countplot</code> of the <code>'education'</code> bill, generated from the following code:</p>
<pre><code>plt.figure()
sns.countplot(x='education', hue='party', data=df, palette='RdBu')
plt.xticks([0,1], ['No', 'Yes'])
plt.show()
</code></pre>
<p>In <code>sns.countplot()</code>, we specify the x-axis data to be <code>'education'</code>, and hue to be <code>'party'</code>. Recall that <code>'party'</code> is also our target variable. So the resulting plot shows the difference in voting behavior between the two parties for the <code>'education'</code> bill, with each party colored differently. We manually specified the color to be <code>'RdBu'</code>, as the Republican party has been traditionally associated with red, and the Democratic party with blue.</p>
<p>It seems like Democrats voted resoundingly <em>against</em> this bill, compared to Republicans. This is the kind of information that our machine learning model will seek to learn when we try to predict party affiliation solely based on voting behavior. An expert in U.S politics may be able to predict this without machine learning, but probably not instantaneously - and certainly not if we are dealing with hundreds of samples! </p>
<p>In the IPython Shell, explore the voting behavior further by generating countplots for the <code>'satellite'</code> and <code>'missile'</code> bills, and answer the following question: Of these two bills, for which ones do Democrats vote resoundingly in <em>favor</em> of, compared to Republicans? Be sure to begin your plotting statements for each figure with <code>plt.figure()</code> so that a new figure will be set up. Otherwise, your plots will be overlaid onto the same figure.</p>
</div>

```{python}
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure()
sns.countplot(x='education', hue='party', data=df, palette='RdBu')
plt.xticks([0,1], ['No', 'Yes'])
plt.show()
```

- [ ] <code>'satellite'</code>
- [ ] <code>'missile'</code>
- [x] Both <code>'satellite'</code> and <code>'missile'</code>.
- [ ] Neither <code>'satellite'</code> nor <code>'missile'</code>.

<p class="">Correct! Democrats voted in favor of both <code>'satellite'</code> <em>and</em> <code>'missile'</code></p>

#### The classification challenge {.unnumbered}



##### k-Nearest Neighbors: Fit {.unnumbered}


<div class>
<p>Having explored the Congressional voting records dataset, it is time now to build your first classifier. In this exercise, you will fit a k-Nearest Neighbors classifier to the voting dataset, which has once again been pre-loaded for you into a DataFrame <code>df</code>. </p>
<p>In the video, Hugo discussed the importance of ensuring your data adheres to the format required by the scikit-learn API. The features need to be in an array where each column is a feature and each row a different observation or data point - in this case, a Congressman's voting record. The target needs to be a single column with the same number of observations as the feature data. We have done this for you in this exercise. Notice we named the feature array <code>X</code> and response variable <code>y</code>: This is in accordance with the common scikit-learn practice.</p>
<p>Your job is to create an instance of a k-NN classifier with 6 neighbors (by specifying the <code>n_neighbors</code> parameter) and then fit it to the data. The data has been pre-loaded into a DataFrame called <code>df</code>.</p>
</div>

<li>Import <code>KNeighborsClassifier</code> from <code>sklearn.neighbors</code>.</li>

<li>Create arrays <code>X</code> and <code>y</code> for the features and the target variable. Here this has been done for you. Note the use of <code>.drop()</code> to drop the target variable <code>'party'</code> from the feature array <code>X</code> as well as the use of the <code>.values</code> attribute to ensure <code>X</code> and <code>y</code> are NumPy arrays. Without using <code>.values</code>, <code>X</code> and <code>y</code> are a DataFrame and Series respectively; the scikit-learn API will accept them in this form also as long as they are of the right shape.</li>

<li>Instantiate a <code>KNeighborsClassifier</code> called <code>knn</code> with <code>6</code> neighbors by specifying the <code>n_neighbors</code> parameter.</li>

<li>Fit the classifier to the data using the <code>.fit()</code> method.</li>
```{python}
# edited/added
import pandas as pd
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/votes-ch1.csv')

# Import KNeighborsClassifier from sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier 

# Create arrays for the features and the response variable
y = df['party'].values
X = df.drop('party', axis=1).values

# Create a k-NN classifier with 6 neighbors
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the data
knn.fit(X, y)
```

<p class="">Excellent! Now that your k-NN classifier with 6 neighbors has been fit to the data, it can be used to predict the labels of new data points.</p>

##### k-Nearest Neighbors: Predict {.unnumbered}


<div class>
<p>Having fit a k-NN classifier, you can now use it to predict the label of a new data point. However, there is no unlabeled data available since all of it was used to fit the model! You can still use the <code>.predict()</code> method on the <code>X</code> that was used to fit the model, but it is not a good indicator of the model's ability to generalize to new, unseen data. </p>
<p>In the next video, Hugo will discuss a solution to this problem. For now, a random unlabeled data point has been generated and is available to you as <code>X_new</code>. You will use your classifier to predict the label for this new data point, as well as on the training data <code>X</code> that the model has already seen. Using <code>.predict()</code> on <code>X_new</code> will generate 1 prediction, while using it on <code>X</code> will generate 435 predictions: 1 for each sample.</p>
<p>The DataFrame has been pre-loaded as <code>df</code>. This time, you will create the feature array <code>X</code> and target variable array <code>y</code> yourself.</p>
</div>


<li>Create arrays for the features and the target variable from <code>df</code>. As a reminder, the target variable is <code>'party'</code>.</li>
```{python}


```
<li>Instantiate a <code>KNeighborsClassifier</code> with <code>6</code> neighbors.</li>

<li>Fit the classifier to the data.</li>

<li>Predict the labels of the training data, <code>X</code>.</li>

<li>Predict the label of the new data point <code>X_new</code>.</li>
```{python}
# edited/added
import numpy as np
X_new = pd.DataFrame((np.random.rand(1,16))) 

# Import KNeighborsClassifier from sklearn.neighbors
from sklearn.neighbors import KNeighborsClassifier 

# Create arrays for the features and the response variable
y = df['party'].values
X = df.drop('party', axis=1).values

# Create a k-NN classifier with 6 neighbors: knn
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the data
knn.fit(X, y)

# Predict the labels for the training data X: y_pred
y_pred = knn.predict(X)

# Predict the labels for the training data X
y_pred = knn.predict(X)

# Predict and print the label for the new data point X_new
new_prediction = knn.predict(X_new)
print("Prediction: {}".format(new_prediction)) 
```

<p class="">Great work! Did your model predict <code>'democrat'</code> or <code>'republican'</code>? How sure can you be of its predictions? In other words, how can you measure its performance? This is what you will learn in the next video.</p>

#### Measuring model performance {.unnumbered}



##### The digits recognition dataset {.unnumbered}


<div class>
<p>Up until now, you have been performing binary classification, since the target variable had two possible outcomes. Hugo, however, got to perform
multi-class classification in the videos, where the target variable could take on three possible outcomes. Why does he get to have all the fun?!
In the following exercises, you'll be working with the <a href="http://yann.lecun.com/exdb/mnist/">MNIST</a> digits recognition dataset, which has
10 classes, the digits 0 through 9! A reduced version of the MNIST dataset is one of scikit-learn's included datasets, and that is the one we will use in this exercise. </p>
<p>Each sample in this scikit-learn dataset is an 8x8 image representing a handwritten digit. Each pixel is represented by an integer in the range 0 to 16, indicating varying levels of black. Recall that scikit-learn's built-in datasets are of type <code>Bunch</code>, which are dictionary-like objects. Helpfully for the MNIST dataset, scikit-learn provides an <code>'images'</code> key in addition to the <code>'data'</code> and <code>'target'</code> keys that you have seen with the Iris data. Because it is a 2D array of the images corresponding to each sample, this <code>'images'</code> key is useful for visualizing the images, as you'll see in this exercise (for more on plotting 2D arrays, see <a href="https://www.datacamp.com/courses/introduction-to-data-visualization-with-python">Chapter 2</a> of DataCamp's course on Data Visualization with Python). On the other hand, the <code>'data'</code> key contains the feature array - that is, the images as a flattened array of 64 pixels.</p>
<p>Notice that you can access the keys of these <code>Bunch</code> objects in two different ways: By using the <code>.</code> notation, as in <code>digits.images</code>, or the <code>[]</code> notation, as in <code>digits['images']</code>. </p>
<p>For more on the MNIST data, check out <a href="https://campus.datacamp.com/courses/importing-data-in-python-part-1/introduction-and-flat-files-1?ex=10">this exercise</a> in Part 1 of DataCamp's Importing Data in Python course. There, the full version of the MNIST dataset is used, in which the images are 28x28. It is a famous dataset in machine learning and computer vision, and frequently used as a benchmark to evaluate the performance of a new model.</p>
</div>

<li>Import <code>datasets</code> from <code>sklearn</code> and <code>matplotlib.pyplot</code> as <code>plt</code>.</li>

<li>Load the digits dataset using the <code>.load_digits()</code> method on <code>datasets</code>.</li>

<li>Print the keys and <code>DESCR</code> of digits.</li>

<li>Print the shape of <code>images</code> and <code>data</code> keys using the <code>.</code> notation.</li>

<li>Display the 1011th image using <code>plt.imshow()</code>. This has been done for you, so hit submit to see which handwritten digit this happens to be!</li>
```{python}
# Import necessary modules
from sklearn import datasets
import matplotlib.pyplot as plt

# Load the digits dataset: digits
digits = datasets.load_digits()

# Print the keys and DESCR of the dataset
print(digits.keys())
print(digits.DESCR)

# Print the shape of the images and data keys
print(digits.images.shape)
print(digits.data.shape)

# Display digit 1010
plt.imshow(digits.images[1010], cmap=plt.cm.gray_r, interpolation='nearest')
plt.show()
```

<p class="">Good job! It looks like the image in question corresponds to the digit '5'. Now, can you build a classifier that can make this prediction not only for this image, but for all the other ones in the dataset? You'll do so in the next exercise!</p>

##### Train/Test Split + Fit/Predict/Accuracy {.unnumbered}


<div class><p>Now that you have learned about the importance of splitting your data into training and test sets, it's time to practice doing this on the digits dataset! After creating arrays for the features and target variable, you will split them into training and test sets, fit a k-NN classifier to the training data, and then compute its accuracy using the <code>.score()</code> method.</p></div>

<li>Import <code>KNeighborsClassifier</code> from <code>sklearn.neighbors</code> and <code>train_test_split</code> from <code>sklearn.model_selection</code>.</li>
```{python}


```
<li>Create an array for the features using <code>digits.data</code> and an array for the target using <code>digits.target</code>.</li>

<li>Create stratified training and test sets using <code>0.2</code> for the size of the test set. Use a random state of <code>42</code>. Stratify the split according to the labels so that they are distributed in the training and test sets as they are in the original dataset.</li>

<li>Create a k-NN classifier with <code>7</code> neighbors and fit it to the training data.</li>

<li>Compute and print the accuracy of the classifier's predictions using the <code>.score()</code> method.</li>
```{python}
# Import necessary modules
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split

# Create feature and target arrays
X = digits.data
y = digits.target

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)


# Create a k-NN classifier with 7 neighbors: knn
knn = KNeighborsClassifier(n_neighbors=7)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Print the accuracy
print(knn.score(X_test, y_test))
```

<p class="">Excellent work! Incredibly, this out of the box k-NN classifier with 7 neighbors has learned from the training data and predicted the labels of the images in the test set with 98% accuracy, and it did so in less than a second! This is one illustration of how incredibly useful machine learning techniques can be.</p>

##### Overfitting and underfitting {.unnumbered}


<div class>
<p>Remember the model complexity curve that Hugo showed in the video? You will now construct such a curve for the digits dataset! In this exercise, you will compute and plot the training and testing accuracy scores for a variety of different neighbor values. By observing how the accuracy scores differ for the training and testing sets with different values of k, you will develop your intuition for overfitting and underfitting.</p>
<p>The training and testing sets are available to you in the workspace as <code>X_train</code>, <code>X_test</code>, <code>y_train</code>, <code>y_test</code>. In addition, <code>KNeighborsClassifier</code> has been imported from <code>sklearn.neighbors</code>.</p>
</div>

<li>Inside the for loop:<ul>
<li>Setup a k-NN classifier with the number of neighbors equal to <code>k</code>.</li>

<li>Fit the classifier with <code>k</code> neighbors to the training data.</li>

<li>Compute accuracy scores the training set and test set separately using the <code>.score()</code> method and assign the results to the <code>train_accuracy</code> and <code>test_accuracy</code> arrays respectively.</li>

</ul>
</li>


```{python}
# Setup arrays to store train and test accuracies
neighbors = np.arange(1, 9)
train_accuracy = np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

# Loop over different values of k
for i, k in enumerate(neighbors):
    # Setup a k-NN Classifier with k neighbors: knn
    knn = KNeighborsClassifier(n_neighbors=k)

    # Fit the classifier to the training data
    knn.fit(X_train, y_train)
    
    #Compute accuracy on the training set
    train_accuracy[i] = knn.score(X_train, y_train)

    #Compute accuracy on the testing set
    test_accuracy[i] = knn.score(X_test, y_test)
    
# Generate plot
plt.title('k-NN: Varying Number of Neighbors')
plt.plot(neighbors, test_accuracy, label = 'Testing Accuracy')
plt.plot(neighbors, train_accuracy, label = 'Training Accuracy')
plt.legend()
plt.xlabel('Number of Neighbors')
plt.ylabel('Accuracy')
plt.show()
```

<p class="">Great work! It looks like the test accuracy is highest when using 3 and 5 neighbors. Using 8 neighbors or more seems to result in a simple model that underfits the data. Now that you've grasped the fundamentals of classification, you will learn about regression in the next chapter!</p>

### Regression {.unnumbered}

<p class="chapter__description">
    In the previous chapter, you used image and political datasets to predict binary and multiclass outcomes. But what if your problem requires a continuous outcome? Regression is best suited to solving such problems. You will learn about fundamental concepts in regression and apply them to predict the life expectancy in a given country using Gapminder data.
  </p>
  
#### Introduction to regression {.unnumbered}



##### Which of the following is a regression problem? {.unnumbered}

<div class=""><p>Andy introduced regression to you using the Boston housing dataset. But regression models can be used in a variety of contexts to solve a variety of different problems.</p>
<p>Given below are four example applications of machine learning. Your job is to pick the one that is <em>best</em> framed as a <strong>regression</strong> problem.</p></div>

- [ ] An e-commerce company using labeled customer data to predict whether or not a customer will purchase a particular item.
- [ ] A healthcare company using data about cancer tumors (such as their geometric measurements) to predict whether a new tumor is benign or malignant.
- [ ] A restaurant using review data to ascribe positive or negative sentiment to a given review.
- [x] A bike share company using time and weather data to predict the number of bikes being rented at any given hour.

<p class="dc-completion-pane__message dc-u-maxw-100pc">Great work! The target variable here - the number of bike rentals at any given hour - is quantitative, so this is best framed as a regression problem.</p>

##### Importing data for supervised learning {.unnumbered}


<div class>
<p>In this chapter, you will work with <a href="https://www.gapminder.org/data/">Gapminder</a> data that we have consolidated into one CSV file available in the workspace as <code>'gapminder.csv'</code>. Specifically, your goal will be to use this data to predict the life expectancy in a given country based on features such as the country's GDP, fertility rate, and population. As in Chapter 1, the dataset has been preprocessed.</p>
<p>Since the target variable here is quantitative, this is a regression problem. To begin, you will fit a linear regression with just one feature: <code>'fertility'</code>, which is the average number of children a woman in a given country gives birth to. In later exercises, you will use all the features to build regression models.</p>
<p>Before that, however, you need to import the data and get it into the form needed by scikit-learn. This involves creating feature and target variable arrays. Furthermore, since you are going to use only one feature to begin with, you need to do some reshaping using NumPy's <code>.reshape()</code> method. Don't worry too much about this reshaping right now, but it is something you will have to do occasionally when working with scikit-learn so it is useful to practice.</p>
</div>

<li>Import <code>numpy</code> and <code>pandas</code> as their standard aliases.</li>

<li>Read the file <code>'gapminder.csv'</code> into a DataFrame <code>df</code> using the <code>read_csv()</code> function.</li>
```{python}



```
<li>Create array <code>X</code> for the <code>'fertility'</code> feature  and array <code>y</code> for the <code>'life'</code> target variable.</li>

<li>Reshape the arrays by using the <code>.reshape()</code> method and passing in <code>-1</code> and <code>1</code>.</li>
```{python}
# Import numpy and pandas
import numpy as np
import pandas as pd

# Read the CSV file into a DataFrame: df
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/gapminder-clean.csv') # edited/added

# Create arrays for features and target variable
y = df['life'].values
X = df['fertility'].values

# Print the dimensions of X and y before reshaping
print("Dimensions of y before reshaping: {}".format(y.shape))
print("Dimensions of X before reshaping: {}".format(X.shape))

# Reshape X and y
y_reshaped = y.reshape(-1, 1)
X_reshaped = X.reshape(-1, 1)

# Print the dimensions of X and y after reshaping
print("Dimensions of y after reshaping: ", y_reshaped.shape)
print("Dimensions of X after reshaping: ", X_reshaped.shape)
```

<p class="">Great work! Notice the differences in shape before and after applying the <code>.reshape()</code> method. Getting the feature and target variable arrays into the right format for scikit-learn is an important precursor to model building.</p>

##### Exploring the Gapminder data {.unnumbered}


<div class>
<p>As always, it is important to explore your data before building models. On the right, we have constructed a heatmap showing the correlation between the different features of the Gapminder dataset, which has been pre-loaded into a DataFrame as <code>df</code> and is available for exploration in the IPython Shell. Cells that are in green show positive correlation, while cells that are in red show negative correlation. Take a moment to explore this: Which features are positively correlated with <code>life</code>, and which ones are negatively correlated? Does this match your intuition? </p>
<p>Then, in the IPython Shell, explore the DataFrame using pandas methods such as <code>.info()</code>, <code>.describe()</code>, <code>.head()</code>. </p>
<p>In case you are curious, the heatmap was generated using <a href="http://seaborn.pydata.org/generated/seaborn.heatmap.html">Seaborn's heatmap function</a> and the following line of code, where <code>df.corr()</code> computes the pairwise correlation between columns:</p>
<p><code>sns.heatmap(df.corr(), square=True, cmap='RdYlGn')</code></p>
<p>Once you have a feel for the data, consider the statements below and select the one that is <strong>not</strong> true. After this, Hugo will explain the mechanics of linear regression in the next video and you will be on your way building regression models!</p>
</div>

```{python}
sns.heatmap(df.corr(), square=True, cmap='RdYlGn')
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.show()
```

- [ ] The DataFrame has <code>139</code> samples (or rows) and <code>9</code> columns.
- [ ] <code>life</code> and <code>fertility</code> are negatively correlated.
- [x] The mean of <code>life</code> is <code>69.602878</code>.
- [ ] <code>GDP</code> and <code>life</code> are positively correlated.



<p class="">Good job! As seen by using <code>df.info()</code>, <code>fertility</code>, along with all the other columns, is of type <code>float64</code>, <strong>not</strong> <code>int64</code>.</p>

#### The basics of linear regression {.unnumbered}



##### Fit &amp; predict for regression {.unnumbered}


<div class>
<p>Now, you will fit a linear regression and predict life expectancy using just one feature. You saw Andy do this earlier using the <code>'RM'</code> feature of the Boston housing dataset. In this exercise, you will use the <code>'fertility'</code> feature of the Gapminder dataset. Since the goal is to predict life expectancy, the target variable here is <code>'life'</code>. The array for the target variable has been pre-loaded as <code>y</code> and the array for <code>'fertility'</code> has been pre-loaded as <code>X_fertility</code>.</p>
<p>A scatter plot with <code>'fertility'</code> on the x-axis and <code>'life'</code> on the y-axis has been generated. As you can see, there is a strongly negative correlation, so a linear regression should be able to capture this trend. Your job is to fit a linear regression and then predict the life expectancy, overlaying these predicted values on the plot to generate a regression line. You will also compute and print the \(R^2\) score using scikit-learn's <code>.score()</code> method.</p>
</div>



<li>Import <code>LinearRegression</code> from <code>sklearn.linear_model</code>.</li>

<li>Create a <code>LinearRegression</code> regressor called <code>reg</code>.</li>

<li>Set up the prediction space to range from the minimum to the maximum of <code>X_fertility</code>. This has been done for you.</li>
```{python}



```
<li>Fit the regressor to the data (<code>X_fertility</code> and <code>y</code>) and compute its predictions using the <code>.predict()</code> method and the <code>prediction_space</code> array.</li>

<li>Compute and print the \(R^2\) score using the <code>.score()</code> method.</li>

<li>Overlay the plot with your linear regression line. This has been done for you, so hit submit to see the result!</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/gapminder-clean.csv')
y = df['life'].values
X = df.drop('life', axis=1)

# Reshape to 1-D
y = y.reshape(-1, 1)
X_fertility = X['fertility'].values.reshape(-1, 1) 

# Import LinearRegression
from sklearn.linear_model import LinearRegression

# Create the regressor: reg
reg = LinearRegression()

# Create the prediction space
prediction_space = np.linspace(min(X_fertility), max(X_fertility)).reshape(-1,1)

# Fit the model to the data
reg.fit(X_fertility, y)

# Compute predictions over the prediction space: y_pred
y_pred = reg.predict(prediction_space)

# Print R^2 
print(reg.score(X_fertility, y))

# Plot regression line
plt.plot(prediction_space, y_pred, color='black', linewidth=3)
plt.show()
```

<p class="">Fantastic! Notice how the line captures the underlying trend in the data. And the performance is quite decent for this basic regression model with only one feature!</p>

##### Train/test split for regression {.unnumbered}


<div class>
<p>As you learned in Chapter 1, train and test sets are vital to ensure that your supervised learning model is able to generalize well to new data. This was true for classification models, and is equally true for linear regression models. </p>
<p>In this exercise, you will split the Gapminder dataset into training and testing sets, and then fit and predict a linear regression over <strong>all</strong> features. In addition to computing the \(R^2\) score, you will also compute the Root Mean Squared Error (RMSE), which is another commonly used metric to evaluate regression models. The feature array <code>X</code> and target variable array <code>y</code> have been pre-loaded for you from the DataFrame <code>df</code>.</p>
</div>

<li>Import <code>LinearRegression</code> from <code>sklearn.linear_model</code>, <code>mean_squared_error</code> from <code>sklearn.metrics</code>, and <code>train_test_split</code> from <code>sklearn.model_selection</code>.</li>

<li>Using <code>X</code> and <code>y</code>, create training and test sets such that 30% is used for testing and 70% for training. Use a random state of <code>42</code>.</li>

<li>Create a linear regression regressor called <code>reg_all</code>, fit it to the training set, and evaluate it on the test set.</li>

<li>Compute and print the \(R^2\) score using the <code>.score()</code> method on the test set.</li>
<li>Compute and print the RMSE. To do this, first compute the Mean Squared Error using the <code>mean_squared_error()</code> function with the arguments <code>y_test</code> and <code>y_pred</code>, and then take its square root using <code>np.sqrt()</code>.</li>
```{python}
# Import necessary modules
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

# Create the regressor: reg_all
reg_all = LinearRegression()

# Fit the regressor to the training data
reg_all.fit(X_train, y_train)

# Predict on the test data: y_pred
y_pred = reg_all.predict(X_test)

# Compute and print R^2 and RMSE
print("R^2: {}".format(reg_all.score(X_test, y_test)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))
```

<p class="">Excellent! Using all features has improved the model score. This makes sense, as the model has more information to learn from. However, there is one potential pitfall to this process. Can you spot it? You'll learn about this as well how to better validate your models in the next video!</p>

#### Cross-validation {.unnumbered}



##### 5-fold cross-validation {.unnumbered}


<div class>
<p>Cross-validation is a vital step in evaluating a model. It maximizes the amount of data that is used to train the model, as during the course of training, the model is not only trained, but also tested on all of the available data.</p>
<p>In this exercise, you will practice 5-fold cross validation on the Gapminder data. By default, scikit-learn's <code>cross_val_score()</code> function uses \(R^2\) as the metric of choice for regression. Since you are performing 5-fold cross-validation, the function will return 5 scores. Your job is to compute these 5 scores and then take their average.</p>
<p>The DataFrame has been loaded as <code>df</code> and split into the feature/target variable arrays <code>X</code> and <code>y</code>. The modules <code>pandas</code> and <code>numpy</code> have been imported as <code>pd</code> and <code>np</code>, respectively.</p>
</div>

<li>Import <code>LinearRegression</code> from <code>sklearn.linear_model</code> and <code>cross_val_score</code> from <code>sklearn.model_selection</code>.</li>

<li>Create a linear regression regressor called <code>reg</code>.</li>

<li>Use the <code>cross_val_score()</code> function to perform 5-fold cross-validation on <code>X</code> and <code>y</code>.</li>

<li>Compute and print the average cross-validation score. You can use NumPy's <code>mean()</code> function to compute the average.</li>
```{python}
# Import the necessary modules
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Create a linear regression object: reg
reg = LinearRegression()

# Compute 5-fold cross-validation scores: cv_scores
cv_scores = cross_val_score(reg, X, y, cv=5)

# Print the 5-fold cross-validation scores
print(cv_scores)

# Print the average 5-fold cross-validation score
print("Average 5-Fold CV Score: {}".format(np.mean(cv_scores)))
```

<p class="">Great work! Now that you have cross-validated your model, you can more confidently evaluate its predictions.</p>

##### K-Fold CV comparison {.unnumbered}


<div class>
<p>Cross validation is essential but do not forget that the more folds you use, the more computationally expensive cross-validation becomes. In this exercise, you will explore this for yourself. Your job is to perform 3-fold cross-validation and then 10-fold cross-validation on the Gapminder dataset.</p>
<p>In the IPython Shell, you can use <code>%timeit</code> to see how long each 3-fold CV takes compared to 10-fold CV by executing the following <code>cv=3</code> and <code>cv=10</code>:</p>
<pre><code>%timeit cross_val_score(reg, X, y, cv = ____)
</code></pre>
<p><code>pandas</code> and <code>numpy</code> are available in the workspace as <code>pd</code> and <code>np</code>. The DataFrame has been loaded as <code>df</code> and the feature/target variable arrays <code>X</code> and <code>y</code> have been created.</p>
</div>

<li>Import <code>LinearRegression</code> from <code>sklearn.linear_model</code> and <code>cross_val_score</code> from <code>sklearn.model_selection</code>. </li>

<li>Create a linear regression regressor called <code>reg</code>.</li>

<li>Perform 3-fold CV and then 10-fold CV. Compare the resulting mean scores.</li>
```{python}
# Import necessary modules
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Create a linear regression object: reg
reg = LinearRegression()

# Perform 3-fold CV
cvscores_3 = cross_val_score(reg, X, y, cv = 3)
print(np.mean(cvscores_3))

# Perform 10-fold CV
cvscores_10 = cross_val_score(reg, X, y, cv = 10)
print(np.mean(cvscores_10))
```

<p class="">Excellent! Did you use <code>%timeit</code> in the IPython Shell to see how much longer it takes 10-fold cross-validation to run compared to 3-fold cross-validation?</p>

#### Regularized regression {.unnumbered}



##### Regularization I: Lasso {.unnumbered}


<div class>
<p>In the video, you saw how Lasso selected out the <code>'RM'</code> feature as being the most important for predicting Boston house prices, while shrinking the coefficients of certain other features to 0. Its ability to perform feature selection in this way becomes even more useful when you are dealing with data involving thousands of features. </p>
<p>In this exercise, you will fit a lasso regression to the Gapminder data you have been working with and plot the coefficients. Just as with the Boston data, you will find that the coefficients of some features are shrunk to 0, with only the most important ones remaining.</p>
<p>The feature and target variable arrays have been pre-loaded as <code>X</code> and <code>y</code>.</p>
</div>


<li>Import <code>Lasso</code> from <code>sklearn.linear_model</code>.</li>
```{python}



```
<li>Instantiate a Lasso regressor with an alpha of <code>0.4</code> and specify <code>normalize=True</code>. </li>

<li>Fit the regressor to the data and compute the coefficients using the <code>coef_</code> attribute.</li>



<li>Plot the coefficients on the y-axis and column names on the x-axis. This has been done for you, so hit submit to view the plot!</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/gapminder-clean.csv')
y = df['life'].values
X = df.drop('life', axis=1).values
df_columns = df.drop('life', axis=1).columns

# Import Lasso
from sklearn.linear_model import Lasso

# Instantiate a lasso regressor: lasso
lasso = Lasso(alpha=0.4, normalize=True)

# Fit the regressor to the data
lasso.fit(X, y)

# Compute and print the coefficients
lasso_coef = lasso.coef_
print(lasso_coef)

# Plot the coefficients
plt.plot(range(len(df_columns)), lasso_coef)
plt.xticks(range(len(df_columns)), df_columns.values, rotation=60)
plt.margins(0.02)
plt.show()
```

<p class="">Great work! According to the lasso algorithm, it seems like <code>'child_mortality'</code> is the most important feature when predicting life expectancy.</p>

##### Regularization II: Ridge {.unnumbered}


<div class>
<p>Lasso is great for feature selection, but when building regression models, Ridge regression should be your first choice.</p>
<p>Recall that lasso performs regularization by adding to the loss function a penalty term of the <em>absolute</em> value of each coefficient multiplied by some alpha. This is also known as \(L1\) regularization because the regularization term is the \(L1\) norm of the coefficients. This is not the only way to regularize, however. </p>
<p>If instead you took the sum of the <em>squared</em> values of the coefficients multiplied by some alpha - like in Ridge regression - you would be computing the \(L2\) norm. In this exercise, you will practice fitting ridge regression models over a range of different alphas, and plot cross-validated \(R^2\) scores for each, using this function that we have defined for you, which plots the \(R^2\) score as well as standard error for each alpha:</p>
<pre><code>def display_plot(cv_scores, cv_scores_std):
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)
    ax.plot(alpha_space, cv_scores)

    std_error = cv_scores_std / np.sqrt(10)

    ax.fill_between(alpha_space, cv_scores + std_error, cv_scores - std_error, alpha=0.2)
    ax.set_ylabel('CV Score +/- Std Error')
    ax.set_xlabel('Alpha')
    ax.axhline(np.max(cv_scores), linestyle='--', color='.5')
    ax.set_xlim([alpha_space[0], alpha_space[-1]])
    ax.set_xscale('log')
    plt.show()
</code></pre>
<p>Don't worry about the specifics of the above function works. The motivation behind this exercise is for you to see how the \(R^2\) score varies with different alphas, and to understand the importance of selecting the right value for alpha. You'll learn how to tune alpha in the next chapter.</p>
</div>

<li>Instantiate a Ridge regressor and specify <code>normalize=True</code>.</li>

<li>Inside the <code>for</code> loop:<ul>
<li>Specify the alpha value for the regressor to use.</li>

<li>Perform 10-fold cross-validation on the regressor with the specified alpha. The data is available in the arrays <code>X</code> and <code>y</code>.</li>

<li>Append the average and the standard deviation of the computed cross-validated scores. NumPy has been pre-imported for you as <code>np</code>.</li>

</ul>
</li>

<li>Use the <code>display_plot()</code> function to visualize the scores and standard deviations.</li>
```{python}
# Import necessary modules
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

# Setup the array of alphas and lists to store scores
alpha_space = np.logspace(-4, 0, 50)
ridge_scores = []
ridge_scores_std = []

# Create a ridge regressor: ridge
ridge = Ridge(normalize=True)

# Compute scores over range of alphas
for alpha in alpha_space:

    # Specify the alpha value to use: ridge.alpha
    ridge.alpha = alpha
    
    # Perform 10-fold CV: ridge_cv_scores
    ridge_cv_scores = cross_val_score(ridge, X, y, cv=10)
    
    # Append the mean of ridge_cv_scores to ridge_scores
    ridge_scores.append(np.mean(ridge_cv_scores))
    
    # Append the std of ridge_cv_scores to ridge_scores_std
    ridge_scores_std.append(np.std(ridge_cv_scores))
    
def display_plot(cv_scores, cv_scores_std):
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)
    ax.plot(alpha_space, cv_scores)

    std_error = cv_scores_std / np.sqrt(10)

    ax.fill_between(alpha_space, cv_scores + std_error, cv_scores - std_error, alpha=0.2)
    ax.set_ylabel('CV Score +/- Std Error')
    ax.set_xlabel('Alpha')
    ax.axhline(np.max(cv_scores), linestyle='--', color='.5')
    ax.set_xlim([alpha_space[0], alpha_space[-1]])
    ax.set_xscale('log')
    plt.show()
    
# Display the plot
display_plot(ridge_scores, ridge_scores_std)
```

<p class="">Great work! Notice how the cross-validation scores change with different alphas. Which alpha should you pick? How can you fine-tune your model? You'll learn all about this in the next chapter!</p>

### Fine-tuning your model {.unnumbered}

<p class="chapter__description">
    Having trained your model, your next task is to evaluate its performance. In this chapter, you will learn about some of the other metrics available in scikit-learn that will allow you to assess your model's performance in a more nuanced manner. Next, learn to optimize your classification and regression models using hyperparameter tuning.
  </p>
  
#### How good is your model? {.unnumbered}



##### Metrics for classification {.unnumbered}


<div class>
<p>In Chapter 1, you evaluated the performance of your k-NN classifier based on its accuracy. However, as Andy discussed, accuracy is not always an informative metric. In this exercise, you will dive more deeply into evaluating the performance of binary classifiers by computing a confusion matrix and generating a classification report. </p>
<p>You may have noticed in the video that the classification report consisted of three rows, and an additional <em>support</em> column. The <em>support</em> gives the number of samples of the true response that lie in that class - so in the video example, the support was the number of Republicans or Democrats in the test set on which the classification report was computed. The <em>precision</em>, <em>recall</em>, and <em>f1-score</em> columns, then, gave the respective metrics for that particular class.</p>
<p>Here, you'll work with the <a href="https://www.kaggle.com/uciml/pima-indians-diabetes-database">PIMA Indians</a> dataset obtained from the UCI Machine Learning Repository. The goal is to predict whether or not a given female patient will contract diabetes based on features such as BMI, age, and number of pregnancies. Therefore, it is a binary classification problem. A target value of <code>0</code> indicates that the patient does <em>not</em> have diabetes, while a value of <code>1</code> indicates that the patient <em>does</em> have diabetes. As in Chapters 1 and 2, the dataset has been preprocessed to deal with missing values.</p>
<p>The dataset has been loaded into a DataFrame <code>df</code> and the feature and target variable arrays <code>X</code> and <code>y</code> have been created for you. In addition, <code>sklearn.model_selection.train_test_split</code> and <code>sklearn.neighbors.KNeighborsClassifier</code> have already been imported.</p>
<p>Your job is to train a k-NN classifier to the data and evaluate its performance by generating a confusion matrix and classification report.</p>
</div>


<li>Import <code>classification_report</code> and <code>confusion_matrix</code> from <code>sklearn.metrics</code>.</li>

<li>Create training and testing sets with 40% of the data used for testing. Use a random state of <code>42</code>.</li>

<li>Instantiate a k-NN classifier with <code>6</code> neighbors, fit it to the training data, and predict the labels of the test set.</li>

<li>Compute and print the confusion matrix and classification report using the <code>confusion_matrix()</code> and <code>classification_report()</code> functions.</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/diabetes.csv')
df.insulin.replace(0, np.nan, inplace=True)
df.triceps.replace(0, np.nan, inplace=True)
df.bmi.replace(0, np.nan, inplace=True)
df.iloc[:, 1:] = df.iloc[:, 1:].apply(lambda x: x.fillna(x.mean()))
y = df['diabetes']
X = df.drop('diabetes', axis=1)

# Import necessary modules
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Create training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

# Instantiate a k-NN classifier: knn
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Predict the labels of the test data: y_pred
y_pred = knn.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
```

<p class="">Excellent work! By analyzing the confusion matrix and classification report, you can get a much better understanding of your classifier's performance.</p>

#### Logistic regression and the ROC curve {.unnumbered}



##### Building a logistic regression model {.unnumbered}


<div class>
<p>Time to build your first logistic regression model! As Hugo showed in the video, scikit-learn makes it very easy to try different models, since the Train-Test-Split/Instantiate/Fit/Predict paradigm applies to all classifiers and regressors - which are known in scikit-learn as 'estimators'. You'll see this now for yourself as you train a logistic regression model on exactly the same data as in the previous exercise. Will it outperform k-NN? There's only one way to find out! </p>
<p>The feature and target variable arrays <code>X</code> and <code>y</code> have been pre-loaded, and <code>train_test_split</code> has been imported for you from <code>sklearn.model_selection</code>.</p>
</div>

<li>Import:<ul>
<li>
<code>LogisticRegression</code> from <code>sklearn.linear_model</code>.</li>

<li>
<code>confusion_matrix</code> and <code>classification_report</code> from <code>sklearn.metrics</code>.</li>

</ul>
</li>

<li>Create training and test sets with 40% (or <code>0.4</code>) of the data used for testing. Use a random state of <code>42</code>. This has been done for you.</li>

<li>Instantiate a <code>LogisticRegression</code> classifier called <code>logreg</code>.</li>

<li>Fit the classifier to the training data and predict the labels of the test set.</li>

<li>Compute and print the confusion matrix and classification report. This has been done for you, so hit submit to see how logistic regression compares to k-NN!</li>
```{python}
# Import the necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

# Create the classifier: logreg
logreg = LogisticRegression()

# Fit the classifier to the training data
logreg.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
```

<p class="">You now know how to use logistic regression for binary classification - great work! Logistic regression is used in a variety of machine learning applications and will become a vital part of your data science toolbox.</p>

##### Plotting an ROC curve {.unnumbered}


<div class>
<p>Great job in the previous exercise - you now have a new addition to your toolbox of classifiers! </p>
<p>Classification reports and confusion matrices are great methods to quantitatively evaluate model performance, while ROC curves provide a way to visually evaluate models. As Hugo demonstrated in the video, most classifiers in scikit-learn have a <code>.predict_proba()</code> method which returns the probability of a given sample being in a particular class. Having built a logistic regression model, you'll now evaluate its performance by plotting an ROC curve. In doing so, you'll make use of the <code>.predict_proba()</code> method and become familiar with its functionality. </p>
<p>Here, you'll continue working with the PIMA Indians diabetes dataset. The classifier has already been fit to the training data and is available as <code>logreg</code>.</p>
</div>

<li>Import <code>roc_curve</code> from <code>sklearn.metrics</code>.</li>

<li>Using the <code>logreg</code> classifier, which has been fit to the training data, compute the predicted probabilities of the labels of the test set <code>X_test</code>. Save the result as <code>y_pred_prob</code>.</li>

<li>Use the <code>roc_curve()</code> function with <code>y_test</code> and <code>y_pred_prob</code> and unpack the result into the variables <code>fpr</code>, <code>tpr</code>, and <code>thresholds</code>.</li>

<li>Plot the ROC curve with <code>fpr</code> on the x-axis and <code>tpr</code> on the y-axis.</li>
```{python}
# Import necessary modules
from sklearn.metrics import roc_curve

# Compute predicted probabilities: y_pred_prob
y_pred_prob = logreg.predict_proba(X_test)[:,1]

# Generate ROC curve values: fpr, tpr, thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)

# Plot ROC curve
plt.plot([0, 1], [0, 1], 'k--')
plt.plot(fpr, tpr)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.show()
```

<p class="">Excellent! This ROC curve provides a nice visual way to assess your classifier's performance.</p>

##### Precision-recall Curve {.unnumbered}


<div class>
<p>When looking at your ROC curve, you may have noticed that the y-axis (True positive rate) is also known as recall. Indeed, in addition to the ROC curve, there are other ways to visually evaluate model performance. One such way is the precision-recall curve, which is generated by plotting the precision and recall for different thresholds. As a reminder, precision and recall are defined as:</p>
<p>$$ Precision = \frac{TP}{TP+FP} $$</p>
<p>$$ Recall = \frac{TP}{TP+FN} $$</p>
<p>On the right, a precision-recall curve has been generated for the diabetes dataset. The classification report and confusion matrix are displayed in the IPython Shell.</p>
<p>Study the precision-recall curve and then consider the statements given below. Choose the one statement that is <strong>not</strong> true. Note that here, the class is positive (1) if the individual <em>has</em> diabetes.</p>
</div>

```{python}
# edited/added
clf = LogisticRegression(solver="liblinear")
clf.fit(X_train, y_train)

from sklearn.metrics import precision_recall_curve
y_pred_prob = clf.predict_proba(X_test)[:,1]
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)

plt.figure(figsize=(6, 6), dpi=None)
plt.plot(recall, precision)
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc='best')
plt.show()
```

- [ ] A recall of 1 corresponds to a classifier with a low threshold in which <em>all</em> females who contract diabetes were correctly classified as such, at the expense of many misclassifications of those who did <em>not</em> have diabetes.
- [ ] Precision is undefined for a classifier which makes <em>no</em> positive predictions, that is, classifies <em>everyone</em> as <em>not</em> having diabetes.
- [ ] When the threshold is very close to 1, precision is also 1, because the classifier is absolutely certain about its predictions.
- [x] Precision and recall take <em>true negatives</em> into consideration.

<p class="">Great work! True negatives do not appear at all in the definitions of precision and recall.</p>

#### Area under the ROC curve {.unnumbered}



##### AUC computation {.unnumbered}


<div class>
<p>Say you have a binary classifier that in fact is just randomly making guesses. It would be correct approximately 50% of the time, and the resulting ROC curve would be a diagonal line in which the True Positive Rate and False Positive Rate are always equal. The Area under this ROC curve would be 0.5. This is one way in which the AUC, which Hugo discussed in the video, is an informative metric to evaluate a model. If the AUC is greater than 0.5, the model is better than random guessing. Always a good sign!  </p>
<p>In this exercise, you'll calculate AUC scores using the <code>roc_auc_score()</code> function from <code>sklearn.metrics</code> as well as by performing cross-validation on the diabetes dataset. </p>
<p><code>X</code> and <code>y</code>, along with training and test sets <code>X_train</code>, <code>X_test</code>, <code>y_train</code>, <code>y_test</code>, have been pre-loaded for you, and a logistic regression classifier <code>logreg</code> has been fit to the training data.</p>
</div>

<li>Import <code>roc_auc_score</code> from <code>sklearn.metrics</code> and <code>cross_val_score</code> from <code>sklearn.model_selection</code>.</li>

<li>Using the <code>logreg</code> classifier, which has been fit to the training data, compute the predicted probabilities of the labels of the test set <code>X_test</code>. Save the result as <code>y_pred_prob</code>.</li>

<li>Compute the AUC score using the <code>roc_auc_score()</code> function, the test set labels <code>y_test</code>, and the predicted probabilities <code>y_pred_prob</code>.</li>

<li>Compute the AUC scores by performing 5-fold cross-validation. Use the <code>cross_val_score()</code> function and specify the <code>scoring</code> parameter to be <code>'roc_auc'</code>.</li>
```{python}
# Import necessary modules
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score

# Compute predicted probabilities: y_pred_prob
y_pred_prob = logreg.predict_proba(X_test)[:,1]

# Compute and print AUC score
print("AUC: {}".format(roc_auc_score(y_test, y_pred_prob)))

# Compute cross-validated AUC scores: cv_auc
cv_auc = cross_val_score(logreg, X, y, cv=5, scoring='roc_auc')

# Print list of AUC scores
print("AUC scores computed using 5-fold cross-validation: {}".format(cv_auc))
```

<p class="">Great work! You now have a number of different methods you can use to evaluate your model's performance.</p>

#### Hyperparameter tuning {.unnumbered}



##### Hyperparameter tuning with GridSearchCV {.unnumbered}


<div class>
<p>Hugo demonstrated how to tune the <code>n_neighbors</code> parameter of the <code>KNeighborsClassifier()</code> using GridSearchCV on the voting dataset. You will now practice this yourself, but by using logistic regression on the diabetes dataset instead! </p>
<p>Like the alpha parameter of lasso and ridge regularization that you saw earlier, logistic regression also has a regularization parameter: \(C\). \(C\) controls the <em>inverse</em> of the regularization strength, and this is what you will tune in this exercise. A large \(C\) can lead to an <em>overfit</em> model, while a small \(C\) can lead to an <em>underfit</em> model.</p>
<p>The hyperparameter space for \(C\) has been setup for you. Your job is to use GridSearchCV and logistic regression to find the optimal \(C\) in this hyperparameter space. The feature array is available as <code>X</code> and target variable array is available as <code>y</code>.</p>
<p>You may be wondering why you aren't asked to split the data into training and test sets. Good observation! Here, we want you to focus on the process of setting up the hyperparameter grid and performing grid-search cross-validation. In practice, you will indeed want to hold out a portion of your data for evaluation purposes, and you will learn all about this in the next video!</p>
</div>

<li>Import <code>LogisticRegression</code> from <code>sklearn.linear_model</code> and <code>GridSearchCV</code> from <code>sklearn.model_selection</code>.</li>

<li>Setup the hyperparameter grid by using <code>c_space</code> as the grid of values to tune \(C\) over.</li>

<li>Instantiate a logistic regression classifier called <code>logreg</code>.</li>

<li>Use <code>GridSearchCV</code> with 5-fold cross-validation to tune \(C\):
<li>Inside <code>GridSearchCV()</code>, specify the classifier, parameter grid, and number of folds to use.</li>

<li>Use the <code>.fit()</code> method on the <code>GridSearchCV</code> object to fit it to the data <code>X</code> and <code>y</code>.</li>


</li>

<li>Print the best parameter and best score obtained from <code>GridSearchCV</code> by accessing the <code>best_params_</code> and <code>best_score_</code> attributes of <code>logreg_cv</code>.</li>
```{python}
# Import necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Setup the hyperparameter grid
c_space = np.logspace(-5, 8, 15)
param_grid = {'C': c_space}

# Instantiate a logistic regression classifier: logreg
logreg = LogisticRegression()

# Instantiate the GridSearchCV object: logreg_cv
logreg_cv = GridSearchCV(logreg, param_grid, cv=5)

# Fit it to the data
logreg_cv.fit(X, y)

# Print the tuned parameter and score
print("Tuned Logistic Regression Parameters: {}".format(logreg_cv.best_params_))
print("Best score is {}".format(logreg_cv.best_score_))
```

<p class="">Good job! It looks like a <code>'C'</code> of <code>3.727</code> results in the best performance.</p>

##### Hyperparameter tuning with RandomizedSearchCV {.unnumbered}


<div class>
<p>GridSearchCV can be computationally expensive, especially if you are searching over a large hyperparameter space and dealing with multiple hyperparameters. A solution to this is to use <code>RandomizedSearchCV</code>, in which not all hyperparameter values are tried out. Instead, a fixed number of hyperparameter settings is sampled from specified probability distributions. You'll practice using <code>RandomizedSearchCV</code> in this exercise and see how this works.</p>
<p>Here, you'll also be introduced to a new model: the Decision Tree. Don't worry about the specifics of how this model works. Just like k-NN, linear regression, and logistic regression, decision trees in scikit-learn have <code>.fit()</code> and <code>.predict()</code> methods that you can use in exactly the same way as before. Decision trees have many parameters that can be tuned, such as <code>max_features</code>, <code>max_depth</code>, and <code>min_samples_leaf</code>: This makes it an ideal use case for <code>RandomizedSearchCV</code>. </p>
<p>As before, the feature array <code>X</code> and target variable array <code>y</code> of the diabetes dataset have been pre-loaded. The hyperparameter settings have been specified for you. Your goal is to use <code>RandomizedSearchCV</code> to find the optimal hyperparameters. Go for it!</p>
</div>

<li>Import <code>DecisionTreeClassifier</code> from <code>sklearn.tree</code> and <code>RandomizedSearchCV</code> from <code>sklearn.model_selection</code>.</li>

<li>Specify the parameters and distributions to sample from. This has been done for you.</li>

<li>Instantiate a <code>DecisionTreeClassifier</code>.</li>

<li>Use <code>RandomizedSearchCV</code> with 5-fold cross-validation to tune the hyperparameters:
<li>Inside <code>RandomizedSearchCV()</code>, specify the classifier, parameter distribution, and number of folds to use.</li>

<li>Use the <code>.fit()</code> method on the <code>RandomizedSearchCV</code> object to fit it to the data <code>X</code> and <code>y</code>.</li>


</li>

<li>Print the best parameter and best score obtained from <code>RandomizedSearchCV</code> by accessing the <code>best_params_</code> and <code>best_score_</code> attributes of <code>tree_cv</code>.</li>
```{python}
# Import necessary modules
from scipy.stats import randint
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV

# Setup the parameters and distributions to sample from: param_dist
param_dist = {"max_depth": [3, None],
              "max_features": randint(1, 9),
              "min_samples_leaf": randint(1, 9),
              "criterion": ["gini", "entropy"]}
              
# Instantiate a Decision Tree classifier: tree
tree = DecisionTreeClassifier()

# Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = RandomizedSearchCV(tree, param_dist, cv=5)

# Fit it to the data
tree_cv.fit(X, y)

# Print the tuned parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

```

<p class="">Great work! You'll see a lot more of decision trees and <code>RandomizedSearchCV</code> as you continue your machine learning journey. Note that <code>RandomizedSearchCV</code> will never outperform <code>GridSearchCV</code>. Instead, it is valuable because it saves on computation time.</p>

#### Hold-out set for final evaluation {.unnumbered}



##### Hold-out set reasoning {.unnumbered}

<p>For which of the following reasons would you want to use a hold-out set for the very end?</p>

- [ ] You want to maximize the amount of training data used.
- [x] You want to be absolutely certain about your model's ability to generalize to unseen data.
- [ ] You want to tune the hyperparameters of your model.

<p class="dc-completion-pane__message dc-u-maxw-100pc">Correct! The idea is to tune the model's hyperparameters on the training set, and then evaluate its performance on the hold-out set which it has never seen before.</p>

##### Hold-out set in practice I: Classification {.unnumbered}


<div class>
<p>You will now practice evaluating a model with tuned hyperparameters on a hold-out set. The feature array and target variable array from the diabetes dataset have been pre-loaded as <code>X</code> and <code>y</code>. </p>
<p>In addition to \(C\), logistic regression has a <code>'penalty'</code> hyperparameter which specifies whether to use <code>'l1'</code> or <code>'l2'</code> regularization. Your job in this exercise is to create a hold-out set, tune the <code>'C'</code> and <code>'penalty'</code> hyperparameters of a logistic regression classifier using <code>GridSearchCV</code> on the training set.</p>
</div>

<li>Create the hyperparameter grid:<ul>
<li>Use the array <code>c_space</code> as the grid of values for <code>'C'</code>.</li>

<li>For <code>'penalty'</code>, specify a list consisting of <code>'l1'</code> and <code>'l2'</code>.</li>

</ul>
</li>

<li>Instantiate a logistic regression classifier.</li>

<li>Create training and test sets. Use a <code>test_size</code> of <code>0.4</code> and <code>random_state</code> of <code>42</code>. In practice, the test set here will function as the hold-out set.</li>

<li>Tune the hyperparameters on the training set using <code>GridSearchCV</code> with 5-folds. This involves first instantiating the <code>GridSearchCV</code> object with the correct parameters and then fitting it to the training data.</li>

<li>Print the best parameter and best score obtained from <code>GridSearchCV</code> by accessing the <code>best_params_</code> and <code>best_score_</code> attributes of <code>logreg_cv</code>.</li>
```{python}
# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Create the hyperparameter grid
c_space = np.logspace(-5, 8, 15)
param_grid = {'C': c_space, 'penalty': ['l1', 'l2']}

# Instantiate the logistic regression classifier: logreg
logreg = LogisticRegression()

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

# Instantiate the GridSearchCV object: logreg_cv
logreg_cv = GridSearchCV(logreg, param_grid, cv=5)

# Fit it to the training data
logreg_cv.fit(X_train, y_train)

# Print the optimal parameters and best score
print("Tuned Logistic Regression Parameter: {}".format(logreg_cv.best_params_))
print("Tuned Logistic Regression Accuracy: {}".format(logreg_cv.best_score_))
```

<p class="">Excellent work! You're really mastering the fundamentals of classification!</p>

##### Hold-out set in practice II: Regression {.unnumbered}


<div class>
<p>Remember lasso and ridge regression from the previous chapter? Lasso used the \(L1\) penalty to regularize, while ridge used the \(L2\) penalty. There is another type of regularized regression known as the elastic net. In elastic net regularization, the penalty term is a linear combination of the \(L1\) and \(L2\) penalties:</p>
<p>$$ a * L1 + b * L2 $$</p>
<p>In scikit-learn, this term is represented by the <code>'l1_ratio'</code> parameter: An <code>'l1_ratio'</code> of <code>1</code> corresponds to an \(L1\) penalty, and anything lower is a combination of \(L1\) and \(L2\).</p>
<p>In this exercise, you will <code>GridSearchCV</code> to tune the <code>'l1_ratio'</code> of an elastic net model trained on the Gapminder data. As in the previous exercise, use a hold-out set to evaluate your model's performance.</p>
</div>


<li>Import the following modules:<ul>
<li>
<code>ElasticNet</code> from <code>sklearn.linear_model</code>.</li>

<li>
<code>mean_squared_error</code> from <code>sklearn.metrics</code>.</li>

<li>
<code>GridSearchCV</code> and <code>train_test_split</code> from <code>sklearn.model_selection</code>.</li>

</ul>
</li>

<li>Create training and test sets, with 40% of the data used for the test set. Use a random state of <code>42</code>.</li>

<li>Specify the hyperparameter grid for <code>'l1_ratio'</code> using <code>l1_space</code> as the grid of values to search over.</li>

<li>Instantiate the <code>ElasticNet</code> regressor. </li>

<li>Use <code>GridSearchCV</code> with 5-fold cross-validation to tune <code>'l1_ratio'</code> on the training data <code>X_train</code> and <code>y_train</code>. This involves first instantiating the <code>GridSearchCV</code> object with the correct parameters and then fitting it to the training data.</li>

<li>Predict on the test set and compute the \(R^2\) and mean squared error.</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/gapminder-clean.csv')
y = df['life'].values
X = df.drop('life', axis=1).values

# Import necessary modules
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

# Create the hyperparameter grid
l1_space = np.linspace(0, 1, 30)
param_grid = {'l1_ratio': l1_space}

# Instantiate the ElasticNet regressor: elastic_net
elastic_net = ElasticNet()

# Setup the GridSearchCV object: gm_cv
gm_cv = GridSearchCV(elastic_net, param_grid, cv=5)

# Fit it to the training data
gm_cv.fit(X_train, y_train)

# Predict on the test set and compute metrics
y_pred = gm_cv.predict(X_test)
r2 = gm_cv.score(X_test, y_test)
mse = mean_squared_error(y_test, y_pred)
print("Tuned ElasticNet l1 ratio: {}".format(gm_cv.best_params_))
print("Tuned ElasticNet R squared: {}".format(r2))
print("Tuned ElasticNet MSE: {}".format(mse))
```

<p class="">Fantastic! Now that you understand how to fine-tune your models, it's time to learn about preprocessing techniques and how to piece together all the different stages of the machine learning process into a pipeline!</p>

### Preprocessing and pipelines {.unnumbered}

<p class="chapter__description">
    This chapter introduces pipelines, and how scikit-learn allows for transformers and estimators to be chained together and used as a single unit. Preprocessing techniques will be introduced as a way to enhance model performance, and pipelines will tie together concepts from previous chapters.
  </p>
  
#### Preprocessing data {.unnumbered}



##### Exploring categorical features {.unnumbered}


<div class>
<p>The Gapminder dataset that you worked with in previous chapters also contained a categorical <code>'Region'</code> feature, which we dropped in previous exercises since you did not have the tools to deal with it. Now however, you do, so we have added it back in! </p>
<p>Your job in this exercise is to explore this feature. Boxplots are particularly useful for visualizing categorical features such as this.</p>
</div>

<li>Import <code>pandas</code> as <code>pd</code>.</li>
```{python}



```
<li>Read the CSV file <code>'gapminder.csv'</code> into a DataFrame called <code>df</code>.</li>

<li>Use pandas to create a boxplot showing the variation of life expectancy (<code>'life'</code>) by region (<code>'Region'</code>). To do so, pass the column names in to <code>df.boxplot()</code> (in that order).</li>
```{python}
# Import pandas
import pandas as pd

# Read 'gapminder.csv' into a DataFrame: df
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/gm_2008_region.csv') # edited/added

# Create a boxplot of life expectancy per region
df.boxplot('life', 'Region', rot=60)

# Show the plot
plt.show()
```

<p class="">Great work! Exploratory data analysis should always be the precursor to model building.</p>

##### Creating dummy variables {.unnumbered}


<div class><p>As Andy discussed in the video, scikit-learn does not accept non-numerical features. You saw in the previous exercise that the <code>'Region'</code> feature contains very useful information that can predict life expectancy. For example, Sub-Saharan Africa has a lower life expectancy compared to Europe and Central Asia. Therefore, if you are trying to predict life expectancy, it would be preferable to retain the <code>'Region'</code> feature. To do this, you need to binarize it by creating dummy variables, which is what you will do in this exercise.</p></div>

<li>Use the pandas <code>get_dummies()</code> function to create dummy variables from the <code>df</code> DataFrame. Store the result as <code>df_region</code>.</li>

<li>Print the columns of <code>df_region</code>. This has been done for you.</li>

<li>Use the <code>get_dummies()</code> function again, this time specifying <code>drop_first=True</code> to drop the unneeded dummy variable (in this case, <code>'Region_America'</code>).</li>

<li>Hit submit to print the new columns of <code>df_region</code> and take note of how one column was dropped!</li>
```{python}
# Create dummy variables: df_region
df_region = pd.get_dummies(df)

# Print the columns of df_region
print(df_region.columns)

# Drop 'Region_America' from df_region
df_region = pd.get_dummies(df, drop_first=True)

# Print the new columns of df_region
print(df_region.columns)
```

<p class="">Excellent! Now that you have created the dummy variables, you can use the <code>'Region'</code> feature to predict life expectancy!</p>

##### Regression with categorical features {.unnumbered}


<div class>
<p>Having created the dummy variables from the <code>'Region'</code> feature, you can build regression models as you did before. Here, you'll use ridge regression to perform 5-fold cross-validation.</p>
<p>The feature array <code>X</code> and target variable array <code>y</code> have been pre-loaded.</p>
</div>


<li>Import <code>Ridge</code> from <code>sklearn.linear_model</code> and <code>cross_val_score</code> from <code>sklearn.model_selection</code>.</li>

<li>Instantiate a ridge regressor called <code>ridge</code> with <code>alpha=0.5</code> and <code>normalize=True</code>.</li>

<li>Perform 5-fold cross-validation on <code>X</code> and <code>y</code> using the <code>cross_val_score()</code> function.</li>

<li>Print the cross-validated scores.</li>
```{python}
# edited/added
X = df_region.drop('life', axis=1).values
y = df_region['life'].values

# Import necessary modules
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Ridge

# Instantiate a ridge regressor: ridge
ridge = Ridge(alpha=0.5, normalize=True)

# Perform 5-fold cross-validation: ridge_cv
ridge_cv = cross_val_score(ridge, X, y, cv=5)

# Print the cross-validated scores
print(ridge_cv)
```

<p class="">Excellent! You now know how to build models using data that includes categorical features.</p>

#### Handling missing data {.unnumbered}



##### Dropping missing data {.unnumbered}


<div class>
<p>The voting dataset from Chapter 1 contained a bunch of missing values that we dealt with for you behind the scenes. Now, it's time for you to take care of these yourself!</p>
<p>The unprocessed dataset has been loaded into a DataFrame <code>df</code>. Explore it in the IPython Shell with the <code>.head()</code> method. You will see that there are certain data points labeled with a <code>'?'</code>. These denote missing values. As you saw in the video, different datasets encode missing values in different ways. Sometimes it may be a <code>'9999'</code>, other times  a <code>0</code> - real-world data can be very messy! If you're lucky, the missing values will already be encoded as <code>NaN</code>. We use <code>NaN</code> because it is an efficient and simplified way of internally representing missing data, and it lets us take advantage of pandas methods such as <code>.dropna()</code> and <code>.fillna()</code>, as well as scikit-learn's Imputation transformer <code>Imputer()</code>.</p>
<p>In this exercise, your job is to convert the <code>'?'</code>s to NaNs, and then drop the rows that contain them from the DataFrame.</p>
</div>


<li>Explore the DataFrame <code>df</code> in the IPython Shell. Notice how the missing value is represented.</li>

<li>Convert all <code>'?'</code> data points to <code>np.nan</code>.</li>

<li>Count the total number of NaNs using the <code>.isnull()</code> and <code>.sum()</code> methods. This has been done for you.</li>

<li>Drop the rows with missing values from <code>df</code> using <code>.dropna()</code>.</li>

<li>Hit submit to see how many rows were lost by dropping the missing values.</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/house-votes-84.csv', header=None, names = ['infants', 'water', 'budget', 'physician', 'salvador', 'religious', 'satellite', 'aid', 'missile', 'immigration', 'synfuels', 'education', 'superfund', 'crime', 'duty_free_exports', 'eaa_rsa'])
df = df.reset_index()
df.rename(columns = {'index': 'party'}, inplace = True)
df[df == 'y'] = 1
df[df == 'n'] = 0

# Convert '?' to NaN
df[df == '?'] = np.nan

# Print the number of NaNs
print(df.isnull().sum())

# Print shape of original DataFrame
print("Shape of Original DataFrame: {}".format(df.shape))

# Drop missing values and print shape of new DataFrame
df = df.dropna()

# Print shape of new DataFrame
print("Shape of DataFrame After Dropping All Rows with Missing Values: {}".format(df.shape))
```

<p class="">Great work! When many values in your dataset are missing, if you drop them, you may end up throwing away valuable information along with the missing data. It's better instead to develop an imputation strategy. This is where domain knowledge is useful, but in the absence of it, you can impute missing values with the mean or the median of the row or column that the missing value is in.</p>

##### Imputing missing data in a ML Pipeline I {.unnumbered}


<div class>
<p>As you've come to appreciate, there are many steps to building a model, from creating training and test sets, to fitting a classifier or regressor, to tuning its parameters, to evaluating its performance on new data. Imputation can be seen as the first step of this machine learning process, the entirety of which can be viewed within the context of a pipeline. Scikit-learn provides a pipeline constructor that allows you to piece together these steps into one process and thereby simplify your workflow. </p>
<p>You'll now practice setting up a pipeline with two steps: the imputation step, followed by the instantiation of a classifier. You've seen three classifiers in this course so far: k-NN, logistic regression, and the decision tree. You will now be introduced to a fourth one - the Support Vector Machine, or <a href="http://scikit-learn.org/stable/modules/svm.html">SVM</a>. For now, do not worry about how it works under the hood. It works exactly as you would expect of the scikit-learn estimators that you have worked with previously, in that it has the same <code>.fit()</code> and <code>.predict()</code> methods as before.</p>
</div>

<li>Import <code>Imputer</code> from <code>sklearn.preprocessing</code> and <code>SVC</code> from <code>sklearn.svm</code>. SVC stands for Support Vector Classification, which is a type of SVM.</li>

<li>Setup the Imputation transformer to impute missing data (represented as <code>np.nan</code>) with the <code>'most_frequent'</code> value in the column (<code>axis=0</code>).</li>

<li>Instantiate a <code>SVC</code> classifier. Store the result in <code>clf</code>.</li>

<li>Create the steps of the pipeline by creating a list of tuples:
<li>The first tuple should consist of the imputation step, using <code>imp</code>.</li>
<li>The second should consist of the classifier.</li>


</li>
```{python}
from sklearn.impute import SimpleImputer as Imputer
from sklearn.svm import SVC

# Setup the Imputation transformer: imp
imp = Imputer(missing_values=np.nan, strategy='most_frequent')

# Instantiate the SVC classifier: clf
clf = SVC()

# Setup the pipeline with the required steps: steps
steps = [('imputation', imp),
        ('SVM', clf)]
```

<p class="">Fantastic! Having set up the pipeline steps, you can now use it for classification.</p>

##### Imputing missing data in a ML Pipeline II {.unnumbered}


<div class>
<p>Having setup the steps of the pipeline in the previous exercise, you will now use it on the voting dataset to classify a Congressman's party affiliation. What makes pipelines so incredibly useful is the simple interface that they provide. You can use the <code>.fit()</code> and <code>.predict()</code> methods on pipelines just as you did with your classifiers and regressors! </p>
<p>Practice this for yourself now and generate a classification report of your predictions. The steps of the pipeline have been set up for you, and the feature array <code>X</code> and target variable array <code>y</code> have been pre-loaded. Additionally, <code>train_test_split</code> and <code>classification_report</code> have been imported from <code>sklearn.model_selection</code> and <code>sklearn.metrics</code> respectively.</p>
</div>


<li>Import the following modules:<ul>
<li>
<code>Imputer</code> from <code>sklearn.preprocessing</code> and <code>Pipeline</code> from <code>sklearn.pipeline</code>.</li>

<li>
<code>SVC</code> from <code>sklearn.svm</code>.</li>

</ul>
</li>

<li>Create the pipeline using <code>Pipeline()</code> and <code>steps</code>.</li>

<li>Create training and test sets. Use 30% of the data for testing and a random state of <code>42</code>.</li>

<li>Fit the pipeline to the training set and predict the labels of the test set.</li>

<li>Compute the classification report.</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/votes-ch1.csv')

# Create arrays for the features and the response variable. As a reminder, the response variable is 'party'
y = df['party']
X = df.drop('party', axis=1)

# Import necessary modules
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

# Setup the pipeline steps: steps
steps = [('imputation', Imputer(missing_values=np.nan, strategy='most_frequent')),
        ('SVM', SVC())]
        
# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Fit the pipeline to the train set
pipeline.fit(X_train, y_train)

# Predict the labels of the test set
y_pred = pipeline.predict(X_test)

# Compute metrics
print(classification_report(y_test, y_pred))
```

<p class="">Great work! Your pipeline has performed imputation as well as classification!</p>

#### Centering and scaling {.unnumbered}



##### Centering and scaling your data {.unnumbered}


<div class>
<p>In the video, Hugo demonstrated how significantly the performance of a model can improve if the features are scaled. Note that this is not always the case: In the Congressional voting records dataset, for example, all of the features are binary. In such a situation, scaling will have minimal impact.</p>
<p>You will now explore scaling for yourself on a new dataset - <a href="https://archive.ics.uci.edu/ml/datasets/Wine+Quality">White Wine Quality</a>! Hugo used the Red Wine Quality dataset in the video. We have used the <code>'quality'</code> feature of the wine to create a binary target variable: If <code>'quality'</code> is less than <code>5</code>, the target variable is <code>1</code>, and otherwise, it is <code>0</code>.</p>
<p>The DataFrame has been pre-loaded as <code>df</code>, along with the feature and target variable arrays <code>X</code> and <code>y</code>. Explore it in the IPython Shell. Notice how some features seem to have different units of measurement. <code>'density'</code>, for instance, takes values between 0.98 and 1.04, while <code>'total sulfur dioxide'</code> ranges from 9 to 440. As a result, it may be worth scaling the features here. Your job in this exercise is to scale the features and compute the mean and standard deviation of the unscaled features compared to the scaled features.</p>
</div>


<li>Import <code>scale</code> from <code>sklearn.preprocessing</code>.</li>

<li>Scale the features <code>X</code> using <code>scale()</code>.</li>

<li>Print the mean and standard deviation of the unscaled features <code>X</code>, and then the scaled features <code>X_scaled</code>. Use the numpy functions <code>np.mean()</code> and <code>np.std()</code> to compute the mean and standard deviations.</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/white-wine.csv')
X = df.drop('quality' , 1).values # drop target variable
y1 = df['quality'].values
y = y1 <= 5

# Import scale
from sklearn.preprocessing import scale

# Scale the features: X_scaled
X_scaled = scale(X)

# Print the mean and standard deviation of the unscaled features
print("Mean of Unscaled Features: {}".format(np.mean(X))) 
print("Standard Deviation of Unscaled Features: {}".format(np.std(X)))

# Print the mean and standard deviation of the scaled features
print("Mean of Scaled Features: {}".format(np.mean(X_scaled))) 
print("Standard Deviation of Scaled Features: {}".format(np.std(X_scaled)))
```

<p class="">Great work! Notice the difference in the mean and standard deviation of the scaled features compared to the unscaled features.</p>

##### Centering and scaling in a pipeline {.unnumbered}


<div class>
<p>With regard to whether or not scaling is effective, the proof is in the pudding! See for yourself whether or not scaling the features of the White Wine Quality dataset has any impact on its performance. You will use a k-NN classifier as part of a pipeline that includes scaling, and for the purposes of comparison, a k-NN classifier trained on the unscaled data has been provided. </p>
<p>The feature array and target variable array have been pre-loaded as <code>X</code> and <code>y</code>. Additionally, <code>KNeighborsClassifier</code> and <code>train_test_split</code> have been imported from <code>sklearn.neighbors</code> and <code>sklearn.model_selection</code>, respectively.</p>
</div>


<li>Import the following modules:<ul>
<li>
<code>StandardScaler</code> from <code>sklearn.preprocessing</code>.</li>

<li>
<code>Pipeline</code> from <code>sklearn.pipeline</code>.</li>

</ul>
</li>

<li>Complete the steps of the pipeline with <code>StandardScaler()</code> for <code>'scaler'</code> and <code>KNeighborsClassifier()</code> for <code>'knn'</code>.</li>

<li>Create the pipeline using <code>Pipeline()</code> and <code>steps</code>.</li>

<li>Create training and test sets, with 30% used for testing. Use a random state of <code>42</code>.</li>

<li>Fit the pipeline to the training set.</li>

<li>Compute the accuracy scores of the scaled and unscaled models by using the <code>.score()</code> method inside the provided <code>print()</code> functions.</li>
```{python}
# edited/added
import pandas as pd
df = pd.read_csv('https://s3.amazonaws.com/assets.datacamp.com/production/course_3238/datasets/white-wine.csv')
X = df.drop('quality' , 1).values # drop target variable
y1 = df['quality'].values
y = y1 <= 5

# Import the necessary modules
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Setup the pipeline steps: steps
steps = [('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier())]
        
# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Fit the pipeline to the training set: knn_scaled
knn_scaled = pipeline.fit(X_train, y_train)

# Instantiate and fit a k-NN classifier to the unscaled data
knn_unscaled = KNeighborsClassifier().fit(X_train, y_train)

# Compute and print metrics
print('Accuracy with Scaling: {}'.format(knn_scaled.score(X_test, y_test)))
print('Accuracy without Scaling: {}'.format(knn_unscaled.score(X_test, y_test)))
```

<p class="">Fantastic! It looks like scaling has significantly improved model performance!</p>

##### Bringing it all together I: Pipeline for classification {.unnumbered}


<div class>
<p>It is time now to piece together everything you have learned so far into a pipeline for classification! Your job in this exercise is to build a pipeline that includes scaling and hyperparameter tuning to classify wine quality.</p>
<p>You'll return to using the SVM classifier you were briefly introduced to earlier in this chapter. The hyperparameters you will tune are \(C\) and \(gamma\). \(C\) controls the regularization strength. It is analogous to the \(C\) you tuned for logistic regression in Chapter 3, while \(gamma\) controls the kernel coefficient: Do not worry about this now as it is beyond the scope of this course. </p>
<p>The following modules and functions have been pre-loaded: <code>Pipeline</code>, <code>SVC</code>, <code>train_test_split</code>, <code>GridSearchCV</code>, <code>classification_report</code>, <code>accuracy_score</code>. The feature and target variable arrays <code>X</code> and <code>y</code> have also been pre-loaded.</p>
</div>

<li>Setup the pipeline with the following steps:<ul>
<li>Scaling, called <code>'scaler'</code> with <code>StandardScaler()</code>.</li>

<li>Classification, called <code>'SVM'</code> with <code>SVC()</code>.</li>

</ul>
</li>

<li>Specify the hyperparameter space using the following notation: <code>'step_name__parameter_name'</code>. Here, the <code>step_name</code> is <code>SVM</code>, and the <code>parameter_name</code>s are <code>C</code> and <code>gamma</code>.</li>

<li>Create training and test sets, with 20% of the data used for the test set. Use a random state of <code>21</code>.</li>

<li>Instantiate <code>GridSearchCV</code> with the pipeline and hyperparameter space and fit it to the training set. Use 3-fold cross-validation (This is the default, so you don't have to specify it).</li>

<li>Predict the labels of the test set and compute the metrics. The metrics have been computed for you.</li>
```{python}
# Setup the pipeline
steps = [('scaler', StandardScaler()),
         ('SVM', SVC())]

pipeline = Pipeline(steps)

# Specify the hyperparameter space
parameters = {'SVM__C':[1, 10, 100],
              'SVM__gamma':[0.1, 0.01]}
              
# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

# Instantiate the GridSearchCV object: cv
cv = GridSearchCV(pipeline, parameters)

# Fit to the training set
cv.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = cv.predict(X_test)

# Compute and print metrics
print("Accuracy: {}".format(cv.score(X_test, y_test)))
print(classification_report(y_test, y_pred))
print("Tuned Model Parameters: {}".format(cv.best_params_))
```

<p class="">Excellent!</p>

##### Bringing it all together II: Pipeline for regression {.unnumbered}


<div class>
<p>For this final exercise, you will return to the Gapminder dataset. Guess what? Even this dataset has missing values that we dealt with for you in earlier chapters! Now, you have all the tools to take care of them yourself! </p>
<p>Your job is to build a pipeline that imputes the missing data, scales the features, and fits an ElasticNet to the Gapminder data. You will then tune the <code>l1_ratio</code> of your ElasticNet using GridSearchCV.</p>
<p>All the necessary modules have been imported, and the feature and target variable arrays have been pre-loaded as <code>X</code> and <code>y</code>.</p>
</div>


<li>Set up a pipeline with the following steps:<ul>
<li>
<code>'imputation'</code>, which uses the <code>Imputer()</code> transformer and the <code>'mean'</code> strategy to impute missing data (<code>np.nan</code>) using the mean of the column.</li>

<li>
<code>'scaler'</code>, which scales the features using <code>StandardScaler()</code>.</li>

<li>
<code>'elasticnet'</code>, which instantiates an <code>ElasticNet()</code> regressor.</li>

</ul>
</li>

<li>Specify the hyperparameter space for the \(l1\) ratio using the following notation: <code>'step_name__parameter_name'</code>. Here, the <code>step_name</code> is <code>elasticnet</code>, and the <code>parameter_name</code> is <code>l1_ratio</code>.</li>

<li>Create training and test sets, with 40% of the data used for the test set. Use a random state of <code>42</code>.</li>

<li>Instantiate <code>GridSearchCV</code> with the pipeline and hyperparameter space. Use 3-fold cross-validation (This is the default, so you don't have to specify it).</li>

<li>Fit the <code>GridSearchCV</code> object to the training set.</li>

<li>Compute \(R^2\) and the best parameters. This has been done for you, so hit submit to see the results!</li>
```{python}
# edited/added
df = pd.read_csv('archive/Machine-Learning-with-scikit-learn/datasets/gapminder.csv')
y = df['life'].values
X = df.drop('life', axis=1).values

# Setup the pipeline steps: steps
steps = [('imputation', Imputer(missing_values=np.nan, strategy='mean')),
         ('scaler', StandardScaler()),
         ('elasticnet', ElasticNet())]
         
# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# Specify the hyperparameter space
parameters = {'elasticnet__l1_ratio':np.linspace(0,1,30)}

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Create the GridSearchCV object: gm_cv
gm_cv = GridSearchCV(pipeline, parameters)

# Fit to the training set
gm_cv.fit(X_train, y_train)

# Compute and print the metrics
r2 = gm_cv.score(X_test, y_test)
print("Tuned ElasticNet Alpha: {}".format(gm_cv.best_params_))
print("Tuned ElasticNet R squared: {}".format(r2))
```

<p class="">Fantastic work! You have now mastered the fundamentals of supervised learning with scikit-learn!</p>

#### Final thoughts {.unnumbered}

##### Final thoughts {.unnumbered}

Congratulations on completing this Introduction to Supervised Learning with scikit-learn. You have sure come a long way.

##### What you’ve learned {.unnumbered}

To recap, you have learnt the fundamentals of using machine learning techniques to build predictive models for both regression and classification problems. You have used these skills to build models using real-world datasets. You have learnt the concepts of underfitting, overfitting. And have learnt the techniques of test-train split, cross-validation, and grid search in order to fine tune your models and report how good they are.

##### What you’ve learned {.unnumbered}

You've also gained first-hand experience at using regularization in your models, seen the utility of lasso and ridge regression, and learnt many types of data pre-processing steps that are essential for any well-rounded data scientist. For more information and examples, check out the scikit-learn documentation and my book, Introduction to Machine Learning with Python.

##### Let's practice! {.unnumbered}

Congratulations once again and we can't wait to see you in more courses.